// ============ ESYA ADI (DIL ANAHTARI) HARITASI ============
// ad_guncelle.py tarafindan Mojang'in resmi en_US.lang dosyasindan
// uretilmistir. ELLE DUZENLEME: uretici yeniden calisinca ustune yazar.
//
// NEDEN: Bedrock'ta esya id'si ile dil anahtari cogu zaman tutmuyor.
//   acacia_planks -> tile.planks.acacia.name   (item.acacia_planks.name YOK)
//   white_wool    -> tile.wool.white.name
//   cod           -> item.fish.name
// Anahtar yoksa Minecraft anahtarin KENDISINI yazar; markette
// "item.acacia_planks.name" gibi okunamaz satirlar cikiyordu.
//
// Buradaki her anahtar Mojang'in kendi lang dosyasinda GERCEKTEN var diye
// dogrulandi. Listede olmayan esya icin main.js id'den okunakli metin
// uretir - ham anahtar asla ekrana gelmez.
//
// Kaynak: v1.21.90.3 + main. 1678 esya cozuldu, 552 cozulemedi.
// Bicim: "<id>=<kod>"  ->  t: = tile.<...>.name , i: = item.<...>.name

const HAM = [
  "acacia_boat=i:boat.acacia acacia_button=t:acacia_button acacia_chest_boat=i:chest_boat.acacia acacia_door=i:acacia_door acacia_double_slab=t:double_wooden_slab.acacia acacia_fence=t:acaciaFence",
  "acacia_fence_gate=t:acacia_fence_gate acacia_hanging_sign=i:acacia_hanging_sign acacia_leaves=t:leaves.acacia acacia_log=t:log.acacia acacia_planks=t:planks.acacia acacia_pressure_plate=t:acacia_pressure_plate",
  "acacia_sapling=t:sapling.acacia acacia_shelf=t:acacia_shelf acacia_sign=i:acacia_sign acacia_slab=t:wooden_slab.acacia acacia_stairs=t:acacia_stairs acacia_standing_sign=t:acacia_standing_sign",
  "acacia_trapdoor=t:acacia_trapdoor acacia_wall_sign=t:acacia_wall_sign acacia_wood=t:wood.acacia activator_rail=t:activator_rail air=i:air allay_spawn_egg=i:spawn_egg.entity.allay",
  "allium=t:red_flower.allium allow=t:allow amethyst_block=t:amethyst_block amethyst_cluster=t:amethyst_cluster amethyst_shard=i:amethyst_shard ancient_debris=t:ancient_debris",
  "andesite=t:stone.andesite andesite_double_slab=t:double_stone_slab3.andesite andesite_slab=t:stone_slab3.andesite andesite_stairs=t:andesite_stairs andesite_wall=t:cobblestone_wall.andesite angler_pottery_sherd=i:angler_pottery_sherd",
  "anvil=t:anvil apple=i:apple archer_pottery_sherd=i:archer_pottery_sherd armadillo_scute=i:armadillo_scute armadillo_spawn_egg=i:spawn_egg.entity.armadillo armor_stand=i:armor_stand",
  "arms_up_pottery_sherd=i:arms_up_pottery_sherd arrow=i:arrow axolotl_bucket=i:bucketAxolotl axolotl_spawn_egg=i:spawn_egg.entity.axolotl azalea=t:azalea azalea_leaves=t:azalea_leaves",
  "azalea_leaves_flowered=t:azalea_leaves_flowered azure_bluet=t:red_flower.houstonia baked_potato=i:baked_potato bamboo=t:bamboo bamboo_block=t:bamboo_block bamboo_boat=i:boat.bamboo",
  "bamboo_button=t:bamboo_button bamboo_chest_boat=i:chest_boat.bamboo bamboo_door=i:bamboo_door bamboo_double_slab=t:bamboo_double_slab bamboo_fence=t:bamboo_fence bamboo_fence_gate=t:bamboo_fence_gate",
  "bamboo_hanging_sign=i:bamboo_hanging_sign bamboo_mosaic=t:bamboo_mosaic bamboo_mosaic_double_slab=t:bamboo_mosaic_double_slab bamboo_mosaic_slab=t:bamboo_mosaic_slab bamboo_mosaic_stairs=t:bamboo_mosaic_stairs bamboo_planks=t:bamboo_planks",
  "bamboo_pressure_plate=t:bamboo_pressure_plate bamboo_raft=i:boat.bamboo bamboo_sapling=t:bamboo_sapling bamboo_shelf=t:bamboo_shelf bamboo_sign=i:bamboo_sign bamboo_slab=t:bamboo_slab",
  "bamboo_stairs=t:bamboo_stairs bamboo_standing_sign=t:bamboo_standing_sign bamboo_trapdoor=t:bamboo_trapdoor bamboo_wall_sign=t:bamboo_wall_sign banner=t:standing_banner barrel=t:barrel",
  "barrier=t:barrier basalt=t:basalt bat_spawn_egg=i:spawn_egg.entity.bat beacon=t:beacon bed=t:bed bedrock=t:bedrock",
  "bee_nest=t:bee_nest bee_spawn_egg=i:spawn_egg.entity.bee beef=i:beef beehive=t:beehive beetroot=i:beetroot beetroot_seeds=i:beetroot_seeds",
  "beetroot_soup=i:beetroot_soup bell=i:bell big_dripleaf=t:big_dripleaf birch_boat=i:boat.birch birch_button=t:birch_button birch_chest_boat=i:chest_boat.birch",
  "birch_door=i:birch_door birch_double_slab=t:double_wooden_slab.birch birch_fence=t:birchFence birch_fence_gate=t:birch_fence_gate birch_hanging_sign=i:birch_hanging_sign birch_leaves=t:leaves.birch",
  "birch_log=t:log.birch birch_planks=t:planks.birch birch_pressure_plate=t:birch_pressure_plate birch_sapling=t:sapling.birch birch_shelf=t:birch_shelf birch_sign=i:birch_sign",
  "birch_slab=t:wooden_slab.birch birch_stairs=t:birch_stairs birch_standing_sign=t:birch_standing_sign birch_trapdoor=t:birch_trapdoor birch_wall_sign=t:birch_wall_sign birch_wood=t:wood.birch",
  "black_banner=i:banner.black black_bed=i:bed.black black_candle=t:black_candle black_candle_cake=t:black_candle_cake black_carpet=t:carpet.black black_concrete=t:concrete.black",
  "black_concrete_powder=t:concretePowder.black black_dye=i:dye.black black_glazed_terracotta=t:glazedTerracottaBlack black_harness=i:black_harness black_shulker_box=t:shulkerBoxBlack black_stained_glass=t:stained_glass.black",
  "black_stained_glass_pane=t:stained_glass_pane.black black_terracotta=t:stained_hardened_clay.black black_wool=t:wool.black blackstone=t:blackstone blackstone_double_slab=t:blackstone_double_slab blackstone_slab=t:blackstone_slab",
  "blackstone_stairs=t:blackstone_stairs blackstone_wall=t:blackstone_wall blade_pottery_sherd=i:blade_pottery_sherd blast_furnace=t:blast_furnace blaze_powder=i:blaze_powder blaze_rod=i:blaze_rod",
  "blaze_spawn_egg=i:spawn_egg.entity.blaze blue_banner=i:banner.blue blue_bed=i:bed.blue blue_candle=t:blue_candle blue_candle_cake=t:blue_candle_cake blue_carpet=t:carpet.blue",
  "blue_concrete=t:concrete.blue blue_concrete_powder=t:concretePowder.blue blue_dye=i:dye.blue blue_egg=i:blue_egg blue_glazed_terracotta=t:glazedTerracottaBlue blue_harness=i:blue_harness",
  "blue_ice=t:blue_ice blue_orchid=t:red_flower.blueOrchid blue_shulker_box=t:shulkerBoxBlue blue_stained_glass=t:stained_glass.blue blue_stained_glass_pane=t:stained_glass_pane.blue blue_terracotta=t:stained_hardened_clay.blue",
  "blue_wool=t:wool.blue bogged_spawn_egg=i:spawn_egg.entity.bogged bolt_armor_trim_smithing_template=i:bolt_armor_trim_smithing_template bone=i:bone bone_block=t:bone_block bone_meal=i:dye.white",
  "book=i:book bookshelf=t:bookshelf border_block=t:border_block bordure_indented_banner_pattern=i:bordure_indented_banner_pattern bow=i:bow bowl=i:bowl",
  "brain_coral=t:coral.pink brain_coral_block=t:coral_block.pink brain_coral_fan=t:coral_fan.pink_fan brain_coral_wall_fan=t:brain_coral_wall_fan bread=i:bread breeze_rod=i:breeze_rod",
  "breeze_spawn_egg=i:spawn_egg.entity.breeze brewer_pottery_sherd=i:brewer_pottery_sherd brewing_stand=i:brewing_stand brick=i:brick brick_block=t:brick_block brick_slab=t:stone_slab.brick",
  "brick_stairs=t:brick_stairs brick_wall=t:cobblestone_wall.brick bricks=t:brick_block brown_banner=i:banner.brown brown_bed=i:bed.brown brown_candle=t:brown_candle",
  "brown_candle_cake=t:brown_candle_cake brown_carpet=t:carpet.brown brown_concrete=t:concrete.brown brown_concrete_powder=t:concretePowder.brown brown_dye=i:dye.brown brown_egg=i:brown_egg",
  "brown_glazed_terracotta=t:glazedTerracottaBrown brown_harness=i:brown_harness brown_mushroom=t:brown_mushroom brown_mushroom_block=t:brown_mushroom_block.cap brown_shulker_box=t:shulkerBoxBrown brown_stained_glass=t:stained_glass.brown",
  "brown_stained_glass_pane=t:stained_glass_pane.brown brown_terracotta=t:stained_hardened_clay.brown brown_wool=t:wool.brown brush=i:brush bubble_column=t:bubble_column bubble_coral=t:coral.purple",
  "bubble_coral_block=t:coral_block.purple bubble_coral_fan=t:coral_fan.purple_fan bubble_coral_wall_fan=t:bubble_coral_wall_fan bucket=i:bucket budding_amethyst=t:budding_amethyst burn_pottery_sherd=i:burn_pottery_sherd",
  "bush=t:bush cactus=t:cactus cactus_flower=t:cactus_flower cake=i:cake calcite=t:calcite calibrated_sculk_sensor=t:calibrated_sculk_sensor",
  "camel_husk_spawn_egg=i:spawn_egg.entity.camel_husk camel_spawn_egg=i:spawn_egg.entity.camel camera=i:camera campfire=t:campfire candle=t:candle candle_cake=t:candle_cake",
  "carrot=i:carrot carrot_on_a_stick=i:carrotOnAStick carrots=t:carrots cartography_table=t:cartography_table carved_pumpkin=t:carved_pumpkin cat_spawn_egg=i:spawn_egg.entity.cat",
  "cauldron=i:cauldron cave_spider_spawn_egg=i:spawn_egg.entity.cave_spider cave_vines=t:cave_vines cave_vines_body_with_berries=t:cave_vines_body_with_berries cave_vines_head_with_berries=t:cave_vines_head_with_berries chain=t:chain",
  "chain_command_block=t:chain_command_block chainmail_boots=i:chainmail_boots chainmail_chestplate=i:chainmail_chestplate chainmail_helmet=i:chainmail_helmet chainmail_leggings=i:chainmail_leggings charcoal=i:charcoal",
  "cherry_boat=i:boat.cherry cherry_button=t:cherry_button cherry_chest_boat=i:chest_boat.cherry cherry_door=i:cherry_door cherry_double_slab=t:cherry_double_slab cherry_fence=t:cherry_fence",
  "cherry_fence_gate=t:cherry_fence_gate cherry_hanging_sign=i:cherry_hanging_sign cherry_leaves=t:cherry_leaves cherry_log=t:cherry_log cherry_planks=t:cherry_planks cherry_pressure_plate=t:cherry_pressure_plate",
  "cherry_sapling=t:cherry_sapling cherry_shelf=t:cherry_shelf cherry_sign=i:cherry_sign cherry_slab=t:cherry_slab cherry_stairs=t:cherry_stairs cherry_standing_sign=t:cherry_standing_sign",
  "cherry_trapdoor=t:cherry_trapdoor cherry_wall_sign=t:cherry_wall_sign cherry_wood=t:cherry_wood chest=t:chest chest_minecart=i:chest_minecart chicken=i:chicken",
  "chicken_spawn_egg=i:spawn_egg.entity.chicken chipped_anvil=t:anvil.slightlyDamaged chiseled_bookshelf=t:chiseled_bookshelf chiseled_cinnabar=t:chiseled_cinnabar chiseled_copper=t:chiseled_copper chiseled_deepslate=t:chiseled_deepslate",
  "chiseled_nether_bricks=t:chiseled_nether_bricks chiseled_polished_blackstone=t:chiseled_polished_blackstone chiseled_quartz_block=t:quartz_block.chiseled chiseled_red_sandstone=t:red_sandstone.chiseled chiseled_resin_bricks=t:chiseled_resin_bricks chiseled_sandstone=t:sandstone.chiseled",
  "chiseled_stone_bricks=t:stonebrick.chiseled chiseled_sulfur=t:chiseled_sulfur chiseled_tuff=t:chiseled_tuff chiseled_tuff_bricks=t:chiseled_tuff_bricks chorus_flower=t:chorus_flower chorus_fruit=i:chorus_fruit",
  "chorus_plant=t:chorus_plant cinnabar=t:cinnabar cinnabar_brick_double_slab=t:cinnabar_brick_double_slab cinnabar_brick_slab=t:cinnabar_brick_slab cinnabar_brick_stairs=t:cinnabar_brick_stairs cinnabar_brick_wall=t:cinnabar_brick_wall",
  "cinnabar_bricks=t:cinnabar_bricks cinnabar_double_slab=t:cinnabar_double_slab cinnabar_slab=t:cinnabar_slab cinnabar_stairs=t:cinnabar_stairs cinnabar_wall=t:cinnabar_wall clay=t:clay",
  "clay_ball=i:clay_ball clock=i:clock closed_eyeblossom=t:closed_eyeblossom coal=i:coal coal_block=t:coal_block coal_ore=t:coal_ore",
  "coarse_dirt=t:dirt.coarse coast_armor_trim_smithing_template=i:coast_armor_trim_smithing_template cobbled_deepslate=t:cobbled_deepslate cobbled_deepslate_double_slab=t:cobbled_deepslate_double_slab cobbled_deepslate_slab=t:cobbled_deepslate_slab cobbled_deepslate_stairs=t:cobbled_deepslate_stairs",
  "cobbled_deepslate_wall=t:cobbled_deepslate_wall cobblestone=t:cobblestone cobblestone_slab=t:stone_slab.cobble cobblestone_stairs=t:stone_stairs cobblestone_wall=t:cobblestone_wall.normal cobweb=t:web",
  "cocoa=t:cocoa cocoa_beans=i:dye.brown cod=i:fish cod_bucket=i:bucketFish cod_spawn_egg=i:spawn_egg.entity.cod command_block=t:command_block",
  "command_block_minecart=i:command_block_minecart comparator=i:comparator compass=i:compass composter=t:composter conduit=t:conduit cooked_beef=i:cooked_beef",
  "cooked_chicken=i:cooked_chicken cooked_cod=i:cooked_fish cooked_mutton=i:muttonCooked cooked_porkchop=i:cooked_porkchop cooked_rabbit=i:cooked_rabbit cooked_salmon=i:cooked_salmon",
  "cookie=i:cookie copper=i:raw_copper copper_axe=i:copper_axe copper_bars=t:copper_bars copper_block=t:copper_block copper_boots=i:copper_boots",
  "copper_bulb=t:copper_bulb copper_chain=t:copper_chain copper_chest=t:copper_chest copper_chestplate=i:copper_chestplate copper_door=i:copper_door copper_golem_spawn_egg=i:spawn_egg.entity.copper_golem",
  "copper_golem_statue=t:copper_golem_statue copper_grate=t:copper_grate copper_helmet=i:copper_helmet copper_hoe=i:copper_hoe copper_horse_armor=i:copper_horse_armor copper_ingot=i:copper_ingot",
  "copper_lantern=t:copper_lantern copper_leggings=i:copper_leggings copper_nautilus_armor=i:copper_nautilus_armor copper_nugget=i:copper_nugget copper_ore=t:copper_ore copper_pickaxe=i:copper_pickaxe",
  "copper_shovel=i:copper_shovel copper_spear=i:copper_spear copper_sword=i:copper_sword copper_torch=t:copper_torch copper_trapdoor=t:copper_trapdoor cornflower=t:red_flower.cornflower",
  "cow_spawn_egg=i:spawn_egg.entity.cow cracked_deepslate_bricks=t:cracked_deepslate_bricks cracked_deepslate_tiles=t:cracked_deepslate_tiles cracked_nether_bricks=t:cracked_nether_bricks cracked_polished_blackstone_bricks=t:cracked_polished_blackstone_bricks cracked_stone_bricks=t:stonebrick.cracked",
  "crafter=t:crafter crafting_table=t:crafting_table creaking_heart=t:creaking_heart creaking_spawn_egg=i:spawn_egg.entity.creaking creeper_banner_pattern=i:creeper_banner_pattern creeper_head=i:skull.creeper",
  "creeper_spawn_egg=i:spawn_egg.entity.creeper crimson_button=t:crimson_button crimson_door=i:crimson_door crimson_double_slab=t:crimson_double_slab crimson_fence=t:crimson_fence crimson_fence_gate=t:crimson_fence_gate",
  "crimson_fungus=t:crimson_fungus crimson_hanging_sign=i:crimson_hanging_sign crimson_hyphae=t:crimson_hyphae crimson_nylium=t:crimson_nylium crimson_planks=t:crimson_planks crimson_pressure_plate=t:crimson_pressure_plate",
  "crimson_roots=t:crimson_roots.crimsonRoots crimson_shelf=t:crimson_shelf crimson_sign=i:crimson_sign crimson_slab=t:crimson_slab crimson_stairs=t:crimson_stairs crimson_standing_sign=t:crimson_standing_sign",
  "crimson_stem=t:crimson_stem crimson_trapdoor=t:crimson_trapdoor crimson_wall_sign=t:crimson_wall_sign crossbow=i:crossbow crying_obsidian=t:crying_obsidian cut_copper=t:cut_copper",
  "cut_copper_slab=t:cut_copper_slab cut_copper_stairs=t:cut_copper_stairs cut_red_sandstone=t:red_sandstone.cut cut_red_sandstone_double_slab=t:double_stone_slab4.cut_red_sandstone cut_red_sandstone_slab=t:stone_slab4.cut_red_sandstone cut_sandstone=t:sandstone.cut",
  "cut_sandstone_double_slab=t:double_stone_slab4.cut_sandstone cut_sandstone_slab=t:stone_slab4.cut_sandstone cyan_banner=i:banner.cyan cyan_bed=i:bed.cyan cyan_candle=t:cyan_candle cyan_candle_cake=t:cyan_candle_cake",
  "cyan_carpet=t:carpet.cyan cyan_concrete=t:concrete.cyan cyan_concrete_powder=t:concretePowder.cyan cyan_dye=i:dye.cyan cyan_glazed_terracotta=t:glazedTerracottaCyan cyan_harness=i:cyan_harness",
  "cyan_shulker_box=t:shulkerBoxCyan cyan_stained_glass=t:stained_glass.cyan cyan_stained_glass_pane=t:stained_glass_pane.cyan cyan_terracotta=t:stained_hardened_clay.cyan cyan_wool=t:wool.cyan damaged_anvil=t:anvil.veryDamaged",
  "dandelion=t:yellow_flower.dandelion danger_pottery_sherd=i:danger_pottery_sherd dark_oak_boat=i:boat.big_oak dark_oak_button=t:dark_oak_button dark_oak_chest_boat=i:chest_boat.big_oak dark_oak_door=i:dark_oak_door",
  "dark_oak_double_slab=t:double_wooden_slab.big_oak dark_oak_fence=t:darkOakFence dark_oak_fence_gate=t:dark_oak_fence_gate dark_oak_hanging_sign=i:dark_oak_hanging_sign dark_oak_leaves=t:leaves.big_oak dark_oak_log=t:log.big_oak",
  "dark_oak_planks=t:planks.big_oak dark_oak_pressure_plate=t:dark_oak_pressure_plate dark_oak_sapling=t:sapling.big_oak dark_oak_shelf=t:dark_oak_shelf dark_oak_sign=i:darkoak_sign dark_oak_slab=t:wooden_slab.big_oak",
  "dark_oak_stairs=t:dark_oak_stairs dark_oak_trapdoor=t:dark_oak_trapdoor dark_oak_wood=t:wood.dark_oak dark_prismarine=t:prismarine.dark dark_prismarine_double_slab=t:double_stone_slab2.prismarine.dark dark_prismarine_slab=t:stone_slab2.prismarine.dark",
  "dark_prismarine_stairs=t:dark_prismarine_stairs darkoak_standing_sign=t:darkoak_standing_sign darkoak_wall_sign=t:darkoak_wall_sign daylight_detector=t:daylight_detector daylight_detector_inverted=t:daylight_detector_inverted dead_brain_coral=t:coral.pink_dead",
  "dead_brain_coral_block=t:coral_block.pink_dead dead_brain_coral_fan=t:coral_fan_dead.pink_fan dead_brain_coral_wall_fan=t:dead_brain_coral_wall_fan dead_bubble_coral=t:coral.purple_dead dead_bubble_coral_block=t:coral_block.purple_dead dead_bubble_coral_fan=t:coral_fan_dead.purple_fan",
  "dead_bubble_coral_wall_fan=t:dead_bubble_coral_wall_fan dead_bush=t:deadbush dead_fire_coral=t:coral.red_dead dead_fire_coral_block=t:coral_block.red_dead dead_fire_coral_fan=t:coral_fan_dead.red_fan dead_fire_coral_wall_fan=t:dead_fire_coral_wall_fan",
  "dead_horn_coral=t:coral.yellow_dead dead_horn_coral_block=t:coral_block.yellow_dead dead_horn_coral_fan=t:coral_fan_dead.yellow_fan dead_horn_coral_wall_fan=t:dead_horn_coral_wall_fan dead_tube_coral=t:coral.blue_dead dead_tube_coral_block=t:coral_block.blue_dead",
  "dead_tube_coral_fan=t:coral_fan_dead.blue_fan dead_tube_coral_wall_fan=t:dead_tube_coral_wall_fan deadbush=t:deadbush decorated_pot=t:decorated_pot deepslate=t:deepslate deepslate_brick_double_slab=t:deepslate_brick_double_slab",
  "deepslate_brick_slab=t:deepslate_brick_slab deepslate_brick_stairs=t:deepslate_brick_stairs deepslate_brick_wall=t:deepslate_brick_wall deepslate_bricks=t:deepslate_bricks deepslate_coal_ore=t:deepslate_coal_ore deepslate_copper_ore=t:deepslate_copper_ore",
  "deepslate_diamond_ore=t:deepslate_diamond_ore deepslate_emerald_ore=t:deepslate_emerald_ore deepslate_gold_ore=t:deepslate_gold_ore deepslate_iron_ore=t:deepslate_iron_ore deepslate_lapis_ore=t:deepslate_lapis_ore deepslate_redstone_ore=t:deepslate_redstone_ore",
  "deepslate_tile_double_slab=t:deepslate_tile_double_slab deepslate_tile_slab=t:deepslate_tile_slab deepslate_tile_stairs=t:deepslate_tile_stairs deepslate_tile_wall=t:deepslate_tile_wall deepslate_tiles=t:deepslate_tiles deny=t:deny",
  "detector_rail=t:detector_rail diamond=i:diamond diamond_axe=i:diamond_axe diamond_block=t:diamond_block diamond_boots=i:diamond_boots diamond_chestplate=i:diamond_chestplate",
  "diamond_helmet=i:diamond_helmet diamond_hoe=i:diamond_hoe diamond_horse_armor=i:horsearmordiamond diamond_leggings=i:diamond_leggings diamond_nautilus_armor=i:diamond_nautilus_armor diamond_ore=t:diamond_ore",
  "diamond_pickaxe=i:diamond_pickaxe diamond_shovel=i:diamond_shovel diamond_spear=i:diamond_spear diamond_sword=i:diamond_sword diorite=t:stone.diorite diorite_double_slab=t:double_stone_slab3.diorite",
  "diorite_slab=t:stone_slab3.diorite diorite_stairs=t:diorite_stairs diorite_wall=t:cobblestone_wall.diorite dirt=t:dirt dirt_with_roots=t:dirt_with_roots dispenser=t:dispenser",
  "dolphin_spawn_egg=i:spawn_egg.entity.dolphin donkey_spawn_egg=i:spawn_egg.entity.donkey double_cut_copper_slab=t:double_cut_copper_slab dragon_breath=i:dragon_breath dragon_egg=t:dragon_egg dragon_head=i:skull.dragon",
  "dried_ghast=t:dried_ghast dried_kelp=i:dried_kelp dried_kelp_block=t:dried_kelp_block dripstone_block=t:dripstone_block dropper=t:dropper drowned_spawn_egg=i:spawn_egg.entity.drowned",
  "dune_armor_trim_smithing_template=i:dune_armor_trim_smithing_template echo_shard=i:echo_shard egg=i:egg elder_guardian_spawn_egg=i:spawn_egg.entity.elder_guardian elytra=i:elytra emerald=i:emerald",
  "emerald_block=t:emerald_block emerald_ore=t:emerald_ore empty_map=i:emptyMap enchanted_book=i:enchanted_book enchanted_golden_apple=i:appleEnchanted enchanting_table=t:enchanting_table",
  "end_brick_stairs=t:end_brick_stairs end_bricks=t:end_bricks end_crystal=i:end_crystal end_portal=t:end_portal end_portal_frame=t:end_portal_frame end_rod=t:end_rod",
  "end_stone=t:end_stone end_stone_brick_double_slab=t:double_stone_slab3.end_brick end_stone_brick_slab=t:stone_slab3.end_brick end_stone_brick_stairs=t:end_brick_stairs end_stone_brick_wall=t:cobblestone_wall.end_brick end_stone_bricks=t:end_bricks",
  "ender_chest=t:ender_chest ender_dragon_spawn_egg=i:spawn_egg.entity.ender_dragon ender_eye=i:ender_eye ender_pearl=i:ender_pearl enderman_spawn_egg=i:spawn_egg.entity.enderman endermite_spawn_egg=i:spawn_egg.entity.endermite",
  "evoker_spawn_egg=i:spawn_egg.entity.evocation_illager experience_bottle=i:experience_bottle explorer_pottery_sherd=i:explorer_pottery_sherd exposed_chiseled_copper=t:exposed_chiseled_copper exposed_copper=t:exposed_copper exposed_copper_bars=t:exposed_copper_bars",
  "exposed_copper_bulb=t:exposed_copper_bulb exposed_copper_chain=t:exposed_copper_chain exposed_copper_chest=t:exposed_copper_chest exposed_copper_door=i:exposed_copper_door exposed_copper_golem_statue=t:exposed_copper_golem_statue exposed_copper_grate=t:exposed_copper_grate",
  "exposed_copper_lantern=t:exposed_copper_lantern exposed_copper_trapdoor=t:exposed_copper_trapdoor exposed_cut_copper=t:exposed_cut_copper exposed_cut_copper_slab=t:exposed_cut_copper_slab exposed_cut_copper_stairs=t:exposed_cut_copper_stairs exposed_double_cut_copper_slab=t:exposed_double_cut_copper_slab",
  "exposed_lightning_rod=t:exposed_lightning_rod eye_armor_trim_smithing_template=i:eye_armor_trim_smithing_template farmland=t:farmland feather=i:feather fence_gate=t:fence_gate fermented_spider_eye=i:fermented_spider_eye",
  "fern=t:tallgrass.fern field_masoned_banner_pattern=i:field_masoned_banner_pattern filled_map=i:map fire=t:fire fire_charge=i:fireball fire_coral=t:coral.red",
  "fire_coral_block=t:coral_block.red fire_coral_fan=t:coral_fan.red_fan fire_coral_wall_fan=t:fire_coral_wall_fan firefly_bush=t:firefly_bush firework_rocket=i:fireworks firework_star=i:fireworksCharge",
  "fishing_rod=i:fishing_rod fletching_table=t:fletching_table flint=i:flint flint_and_steel=i:flint_and_steel flow_armor_trim_smithing_template=i:flow_armor_trim_smithing_template flow_banner_pattern=i:flow_banner_pattern",
  "flow_pottery_sherd=i:flow_pottery_sherd flower_banner_pattern=i:flower_banner_pattern flower_pot=i:flower_pot flowering_azalea=t:flowering_azalea flowing_lava=t:flowing_lava flowing_water=t:flowing_water",
  "fox_spawn_egg=i:spawn_egg.entity.fox frame=i:frame friend_pottery_sherd=i:friend_pottery_sherd frog_spawn=t:frog_spawn frog_spawn_egg=i:spawn_egg.entity.frog frogspawn=t:frog_spawn",
  "frosted_ice=t:frosted_ice furnace=t:furnace ghast_spawn_egg=i:spawn_egg.entity.ghast ghast_tear=i:ghast_tear gilded_blackstone=t:gilded_blackstone glass=t:glass",
  "glass_bottle=i:glass_bottle glass_pane=t:glass_pane glistering_melon_slice=i:speckled_melon globe_banner_pattern=i:globe_banner_pattern glow_berries=i:glow_berries glow_frame=i:glow_frame",
  "glow_ink_sac=i:glow_ink_sac glow_item_frame=i:glow_frame glow_lichen=t:glow_lichen glow_squid_spawn_egg=i:spawn_egg.entity.glow_squid glowstone=t:glowstone glowstone_dust=i:glowstone_dust",
  "goat_horn=i:goat_horn goat_spawn_egg=i:spawn_egg.entity.goat gold_block=t:gold_block gold_ingot=i:gold_ingot gold_nugget=i:gold_nugget gold_ore=t:gold_ore",
  "golden_apple=i:golden_apple golden_axe=i:golden_axe golden_boots=i:golden_boots golden_carrot=i:golden_carrot golden_chestplate=i:golden_chestplate golden_dandelion=t:golden_dandelion",
  "golden_helmet=i:golden_helmet golden_hoe=i:golden_hoe golden_horse_armor=i:horsearmorgold golden_leggings=i:golden_leggings golden_nautilus_armor=i:golden_nautilus_armor golden_pickaxe=i:golden_pickaxe",
  "golden_rail=t:golden_rail golden_shovel=i:golden_shovel golden_spear=i:golden_spear golden_sword=i:golden_sword granite=t:stone.granite granite_double_slab=t:double_stone_slab3.granite",
  "granite_slab=t:stone_slab3.granite granite_stairs=t:granite_stairs granite_wall=t:cobblestone_wall.granite grass=t:grass grass_block=t:grass grass_path=t:grass_path",
  "gravel=t:gravel gray_banner=i:banner.gray gray_bed=i:bed.gray gray_candle=t:gray_candle gray_candle_cake=t:gray_candle_cake gray_carpet=t:carpet.gray",
  "gray_concrete=t:concrete.gray gray_concrete_powder=t:concretePowder.gray gray_dye=i:dye.gray gray_glazed_terracotta=t:glazedTerracottaGray gray_harness=i:gray_harness gray_shulker_box=t:shulkerBoxGray",
  "gray_stained_glass=t:stained_glass.gray gray_stained_glass_pane=t:stained_glass_pane.gray gray_terracotta=t:stained_hardened_clay.gray gray_wool=t:wool.gray green_banner=i:banner.green green_bed=i:bed.green",
  "green_candle=t:green_candle green_candle_cake=t:green_candle_cake green_carpet=t:carpet.green green_concrete=t:concrete.green green_concrete_powder=t:concretePowder.green green_dye=i:dye.green",
  "green_glazed_terracotta=t:glazedTerracottaGreen green_harness=i:green_harness green_shulker_box=t:shulkerBoxGreen green_stained_glass=t:stained_glass.green green_stained_glass_pane=t:stained_glass_pane.green green_terracotta=t:stained_hardened_clay.green",
  "green_wool=t:wool.green grindstone=t:grindstone guardian_spawn_egg=i:spawn_egg.entity.guardian gunpowder=i:gunpowder guster_banner_pattern=i:guster_banner_pattern guster_pottery_sherd=i:guster_pottery_sherd",
  "hanging_roots=t:hanging_roots happy_ghast_spawn_egg=i:spawn_egg.entity.happy_ghast hardened_clay=t:hardened_clay hay_block=t:hay_block heart_of_the_sea=i:heart_of_the_sea heart_pottery_sherd=i:heart_pottery_sherd",
  "heartbreak_pottery_sherd=i:heartbreak_pottery_sherd heavy_core=t:heavy_core heavy_weighted_pressure_plate=t:heavy_weighted_pressure_plate hoglin_spawn_egg=i:spawn_egg.entity.hoglin honey_block=t:honey_block honey_bottle=i:honey_bottle",
  "honeycomb=i:honeycomb honeycomb_block=t:honeycomb_block hopper=t:hopper hopper_minecart=i:hopper_minecart horn_coral=t:coral.yellow horn_coral_block=t:coral_block.yellow",
  "horn_coral_fan=t:coral_fan.yellow_fan horn_coral_wall_fan=t:horn_coral_wall_fan horse_spawn_egg=i:spawn_egg.entity.horse host_armor_trim_smithing_template=i:host_armor_trim_smithing_template howl_pottery_sherd=i:howl_pottery_sherd husk_spawn_egg=i:spawn_egg.entity.husk",
  "ice=t:ice infested_cobblestone=t:monster_egg.cobble infested_deepslate=t:infested_deepslate infested_stone=t:monster_egg infested_stone_bricks=t:monster_egg.brick ink_sac=i:dye.black",
  "iron_axe=i:iron_axe iron_bars=t:iron_bars iron_block=t:iron_block iron_boots=i:iron_boots iron_chain=t:iron_chain iron_chestplate=i:iron_chestplate",
  "iron_door=i:iron_door iron_golem_spawn_egg=i:spawn_egg.entity.iron_golem iron_helmet=i:iron_helmet iron_hoe=i:iron_hoe iron_horse_armor=i:horsearmoriron iron_ingot=i:iron_ingot",
  "iron_leggings=i:iron_leggings iron_nautilus_armor=i:iron_nautilus_armor iron_nugget=i:iron_nugget iron_ore=t:iron_ore iron_pickaxe=i:iron_pickaxe iron_shovel=i:iron_shovel",
  "iron_spear=i:iron_spear iron_sword=i:iron_sword iron_trapdoor=t:iron_trapdoor item_frame=i:frame jack_o_lantern=t:lit_pumpkin jigsaw=t:jigsaw",
  "jukebox=t:jukebox jungle_boat=i:boat.jungle jungle_button=t:jungle_button jungle_chest_boat=i:chest_boat.jungle jungle_door=i:jungle_door jungle_double_slab=t:double_wooden_slab.jungle",
  "jungle_fence=t:jungleFence jungle_fence_gate=t:jungle_fence_gate jungle_hanging_sign=i:jungle_hanging_sign jungle_leaves=t:leaves.jungle jungle_log=t:log.jungle jungle_planks=t:planks.jungle",
  "jungle_pressure_plate=t:jungle_pressure_plate jungle_sapling=t:sapling.jungle jungle_shelf=t:jungle_shelf jungle_sign=i:jungle_sign jungle_slab=t:wooden_slab.jungle jungle_stairs=t:jungle_stairs",
  "jungle_standing_sign=t:jungle_standing_sign jungle_trapdoor=t:jungle_trapdoor jungle_wall_sign=t:jungle_wall_sign jungle_wood=t:wood.jungle kelp=i:kelp ladder=t:ladder",
  "lantern=t:lantern lapis_block=t:lapis_block lapis_lazuli=i:dye.blue lapis_ore=t:lapis_ore large_amethyst_bud=t:large_amethyst_bud large_fern=t:double_plant.fern",
  "lava=t:lava lava_bucket=i:bucketLava lead=i:lead leaf_litter=t:leaf_litter leather=i:leather leather_boots=i:leather_boots",
  "leather_chestplate=i:leather_chestplate leather_helmet=i:leather_helmet leather_horse_armor=i:horsearmorleather leather_leggings=i:leather_leggings lectern=t:lectern lever=t:lever",
  "light_block=t:light_block light_blue_banner=i:banner.lightBlue light_blue_bed=i:bed.lightBlue light_blue_candle=t:light_blue_candle light_blue_candle_cake=t:light_blue_candle_cake light_blue_carpet=t:carpet.lightBlue",
  "light_blue_concrete=t:concrete.lightBlue light_blue_concrete_powder=t:concretePowder.lightBlue light_blue_dye=i:dye.lightBlue light_blue_glazed_terracotta=t:glazedTerracottaLightBlue light_blue_harness=i:light_blue_harness light_blue_shulker_box=t:shulkerBoxLightBlue",
  "light_blue_stained_glass=t:stained_glass.light_blue light_blue_stained_glass_pane=t:stained_glass_pane.light_blue light_blue_terracotta=t:stained_hardened_clay.lightBlue light_blue_wool=t:wool.lightBlue light_gray_banner=i:banner.silver light_gray_bed=i:bed.silver",
  "light_gray_candle=t:light_gray_candle light_gray_candle_cake=t:light_gray_candle_cake light_gray_carpet=t:carpet.silver light_gray_concrete=t:concrete.silver light_gray_concrete_powder=t:concretePowder.silver light_gray_dye=i:dye.silver",
  "light_gray_glazed_terracotta=t:glazedTerracottaSilver light_gray_harness=i:light_gray_harness light_gray_shulker_box=t:shulkerBoxSilver light_gray_stained_glass=t:stained_glass.silver light_gray_stained_glass_pane=t:stained_glass_pane.silver light_gray_terracotta=t:stained_hardened_clay.silver",
  "light_gray_wool=t:wool.silver light_weighted_pressure_plate=t:light_weighted_pressure_plate lightning_rod=t:lightning_rod lilac=t:double_plant.syringa lily_of_the_valley=t:red_flower.lilyOfTheValley lily_pad=t:waterlily",
  "lime_banner=i:banner.lime lime_bed=i:bed.lime lime_candle=t:lime_candle lime_candle_cake=t:lime_candle_cake lime_carpet=t:carpet.lime lime_concrete=t:concrete.lime",
  "lime_concrete_powder=t:concretePowder.lime lime_dye=i:dye.lime lime_glazed_terracotta=t:glazedTerracottaLime lime_harness=i:lime_harness lime_shulker_box=t:shulkerBoxLime lime_stained_glass=t:stained_glass.lime",
  "lime_stained_glass_pane=t:stained_glass_pane.lime lime_terracotta=t:stained_hardened_clay.lime lime_wool=t:wool.lime lit_blast_furnace=t:lit_blast_furnace lit_deepslate_redstone_ore=t:lit_deepslate_redstone_ore lit_furnace=t:lit_furnace",
  "lit_pumpkin=t:lit_pumpkin lit_redstone_lamp=t:lit_redstone_lamp lit_redstone_ore=t:lit_redstone_ore lit_smoker=t:lit_smoker llama_spawn_egg=i:spawn_egg.entity.llama lodestone=t:lodestone",
  "lodestone_compass=i:lodestonecompass loom=t:loom mace=i:mace magenta_banner=i:banner.magenta magenta_bed=i:bed.magenta magenta_candle=t:magenta_candle",
  "magenta_candle_cake=t:magenta_candle_cake magenta_carpet=t:carpet.magenta magenta_concrete=t:concrete.magenta magenta_concrete_powder=t:concretePowder.magenta magenta_dye=i:dye.magenta magenta_glazed_terracotta=t:glazedTerracottaMagenta",
  "magenta_harness=i:magenta_harness magenta_shulker_box=t:shulkerBoxMagenta magenta_stained_glass=t:stained_glass.magenta magenta_stained_glass_pane=t:stained_glass_pane.magenta magenta_terracotta=t:stained_hardened_clay.magenta magenta_wool=t:wool.magenta",
  "magma=t:magma magma_block=t:magma magma_cream=i:magma_cream magma_cube_spawn_egg=i:spawn_egg.entity.magma_cube mangrove_boat=i:boat.mangrove mangrove_button=t:mangrove_button",
  "mangrove_chest_boat=i:chest_boat.mangrove mangrove_door=i:mangrove_door mangrove_double_slab=t:mangrove_double_slab mangrove_fence=t:mangrove_fence mangrove_fence_gate=t:mangrove_fence_gate mangrove_hanging_sign=i:mangrove_hanging_sign",
  "mangrove_leaves=t:mangrove_leaves mangrove_log=t:mangrove_log mangrove_planks=t:mangrove_planks mangrove_pressure_plate=t:mangrove_pressure_plate mangrove_propagule=t:mangrove_propagule mangrove_roots=t:mangrove_roots",
  "mangrove_shelf=t:mangrove_shelf mangrove_sign=i:mangrove_sign mangrove_slab=t:mangrove_slab mangrove_stairs=t:mangrove_stairs mangrove_standing_sign=t:mangrove_standing_sign mangrove_trapdoor=t:mangrove_trapdoor",
  "mangrove_wall_sign=t:mangrove_wall_sign mangrove_wood=t:mangrove_wood map=i:map medium_amethyst_bud=t:medium_amethyst_bud melon_block=t:melon_block melon_seeds=i:melon_seeds",
  "melon_slice=i:melon melon_stem=t:melon_stem milk_bucket=i:milk minecart=i:minecart miner_pottery_sherd=i:miner_pottery_sherd mob_spawner=t:mob_spawner",
  "mojang_banner_pattern=i:mojang_banner_pattern monster_egg=t:monster_egg mooshroom_spawn_egg=i:spawn_egg.entity.mooshroom moss_block=t:moss_block moss_carpet=t:moss_carpet mossy_cobblestone=t:mossy_cobblestone",
  "mossy_cobblestone_double_slab=t:double_stone_slab2.mossy_cobblestone mossy_cobblestone_slab=t:stone_slab2.mossy_cobblestone mossy_cobblestone_stairs=t:mossy_cobblestone_stairs mossy_cobblestone_wall=t:cobblestone_wall.mossy mossy_stone_brick_double_slab=t:double_stone_slab4.mossy_stone_brick mossy_stone_brick_slab=t:stone_slab4.mossy_stone_brick",
  "mossy_stone_brick_stairs=t:mossy_stone_brick_stairs mossy_stone_brick_wall=t:cobblestone_wall.mossy_stone_brick mossy_stone_bricks=t:stonebrick.mossy mourner_pottery_sherd=i:mourner_pottery_sherd mud=t:mud mud_brick_double_slab=t:mud_brick_double_slab",
  "mud_brick_slab=t:mud_brick_slab mud_brick_stairs=t:mud_brick_stairs mud_brick_wall=t:mud_brick_wall mud_bricks=t:mud_bricks muddy_mangrove_roots=t:muddy_mangrove_roots mule_spawn_egg=i:spawn_egg.entity.mule",
  "mushroom_stem=t:brown_mushroom_block.stem mushroom_stew=i:mushroom_stew mutton=i:muttonRaw mycelium=t:mycelium name_tag=i:name_tag nautilus_shell=i:nautilus_shell",
  "nautilus_spawn_egg=i:spawn_egg.entity.nautilus nether_brick=t:nether_brick nether_brick_fence=t:nether_brick_fence nether_brick_slab=t:stone_slab.nether_brick nether_brick_stairs=t:nether_brick_stairs nether_brick_wall=t:cobblestone_wall.nether_brick",
  "nether_bricks=t:nether_brick nether_gold_ore=t:nether_gold_ore nether_quartz_ore=t:quartz_ore nether_sprouts=t:nether_sprouts nether_star=i:netherStar nether_wart=i:nether_wart",
  "nether_wart_block=t:nether_wart_block netherbrick=i:netherbrick netherite_axe=i:netherite_axe netherite_block=t:netherite_block netherite_boots=i:netherite_boots netherite_chestplate=i:netherite_chestplate",
  "netherite_helmet=i:netherite_helmet netherite_hoe=i:netherite_hoe netherite_horse_armor=i:netherite_horse_armor netherite_ingot=i:netherite_ingot netherite_leggings=i:netherite_leggings netherite_nautilus_armor=i:netherite_nautilus_armor",
  "netherite_pickaxe=i:netherite_pickaxe netherite_scrap=i:netherite_scrap netherite_shovel=i:netherite_shovel netherite_spear=i:netherite_spear netherite_sword=i:netherite_sword netherite_upgrade_smithing_template=i:netherite_upgrade_smithing_template",
  "netherrack=t:netherrack normal_stone_stairs=t:normal_stone_stairs note_block=t:noteblock noteblock=t:noteblock oak_boat=i:boat.oak oak_button=t:wooden_button",
  "oak_chest_boat=i:chest_boat.oak oak_door=i:wooden_door oak_double_slab=t:double_wooden_slab.oak oak_fence=t:fence oak_fence_gate=t:fence_gate oak_hanging_sign=i:oak_hanging_sign",
  "oak_leaves=t:leaves.oak oak_log=t:log.oak oak_planks=t:planks.oak oak_pressure_plate=t:wooden_pressure_plate oak_sapling=t:sapling.oak oak_shelf=t:oak_shelf",
  "oak_sign=i:sign oak_slab=t:wooden_slab.oak oak_stairs=t:oak_stairs oak_trapdoor=t:trapdoor oak_wood=t:wood.oak observer=t:observer",
  "obsidian=t:obsidian ocelot_spawn_egg=i:spawn_egg.entity.ocelot ochre_froglight=t:ochre_froglight ominous_bottle=i:ominous_bottle ominous_trial_key=i:ominous_trial_key open_eyeblossom=t:open_eyeblossom",
  "orange_banner=i:banner.orange orange_bed=i:bed.orange orange_candle=t:orange_candle orange_candle_cake=t:orange_candle_cake orange_carpet=t:carpet.orange orange_concrete=t:concrete.orange",
  "orange_concrete_powder=t:concretePowder.orange orange_dye=i:dye.orange orange_glazed_terracotta=t:glazedTerracottaOrange orange_harness=i:orange_harness orange_shulker_box=t:shulkerBoxOrange orange_stained_glass=t:stained_glass.orange",
  "orange_stained_glass_pane=t:stained_glass_pane.orange orange_terracotta=t:stained_hardened_clay.orange orange_tulip=t:red_flower.tulipOrange orange_wool=t:wool.orange oxeye_daisy=t:red_flower.oxeyeDaisy oxidized_chiseled_copper=t:oxidized_chiseled_copper",
  "oxidized_copper=t:oxidized_copper oxidized_copper_bars=t:oxidized_copper_bars oxidized_copper_bulb=t:oxidized_copper_bulb oxidized_copper_chain=t:oxidized_copper_chain oxidized_copper_chest=t:oxidized_copper_chest oxidized_copper_door=i:oxidized_copper_door",
  "oxidized_copper_golem_statue=t:oxidized_copper_golem_statue oxidized_copper_grate=t:oxidized_copper_grate oxidized_copper_lantern=t:oxidized_copper_lantern oxidized_copper_trapdoor=t:oxidized_copper_trapdoor oxidized_cut_copper=t:oxidized_cut_copper oxidized_cut_copper_slab=t:oxidized_cut_copper_slab",
  "oxidized_cut_copper_stairs=t:oxidized_cut_copper_stairs oxidized_double_cut_copper_slab=t:oxidized_double_cut_copper_slab oxidized_lightning_rod=t:oxidized_lightning_rod packed_ice=t:packed_ice packed_mud=t:packed_mud painting=i:painting",
  "pale_hanging_moss=t:pale_hanging_moss pale_moss_block=t:pale_moss_block pale_moss_carpet=t:pale_moss_carpet pale_oak_boat=i:boat.pale_oak pale_oak_button=t:pale_oak_button pale_oak_chest_boat=i:chest_boat.pale_oak",
  "pale_oak_door=i:pale_oak_door pale_oak_double_slab=t:pale_oak_double_slab pale_oak_fence=t:pale_oak_fence pale_oak_fence_gate=t:pale_oak_fence_gate pale_oak_hanging_sign=i:pale_oak_hanging_sign pale_oak_leaves=t:pale_oak_leaves",
  "pale_oak_log=t:pale_oak_log pale_oak_planks=t:pale_oak_planks pale_oak_pressure_plate=t:pale_oak_pressure_plate pale_oak_sapling=t:pale_oak_sapling pale_oak_shelf=t:pale_oak_shelf pale_oak_sign=i:pale_oak_sign",
  "pale_oak_slab=t:pale_oak_slab pale_oak_stairs=t:pale_oak_stairs pale_oak_standing_sign=t:pale_oak_standing_sign pale_oak_trapdoor=t:pale_oak_trapdoor pale_oak_wall_sign=t:pale_oak_wall_sign pale_oak_wood=t:pale_oak_wood",
  "panda_spawn_egg=i:spawn_egg.entity.panda paper=i:paper parched_spawn_egg=i:spawn_egg.entity.parched parrot_spawn_egg=i:spawn_egg.entity.parrot pearlescent_froglight=t:pearlescent_froglight peony=t:double_plant.paeonia",
  "phantom_membrane=i:phantom_membrane phantom_spawn_egg=i:spawn_egg.entity.phantom pig_spawn_egg=i:spawn_egg.entity.pig piglin_banner_pattern=i:piglin_banner_pattern piglin_brute_spawn_egg=i:spawn_egg.entity.piglin_brute piglin_head=i:skull.piglin",
  "piglin_spawn_egg=i:spawn_egg.entity.piglin pillager_spawn_egg=i:spawn_egg.entity.pillager pink_banner=i:banner.pink pink_bed=i:bed.pink pink_candle=t:pink_candle pink_candle_cake=t:pink_candle_cake",
  "pink_carpet=t:carpet.pink pink_concrete=t:concrete.pink pink_concrete_powder=t:concretePowder.pink pink_dye=i:dye.pink pink_glazed_terracotta=t:glazedTerracottaPink pink_harness=i:pink_harness",
  "pink_petals=t:pink_petals pink_shulker_box=t:shulkerBoxPink pink_stained_glass=t:stained_glass.pink pink_stained_glass_pane=t:stained_glass_pane.pink pink_terracotta=t:stained_hardened_clay.pink pink_tulip=t:red_flower.tulipPink",
  "pink_wool=t:wool.pink piston=t:piston piston_arm_collision=t:piston_arm_collision pitcher_crop=t:pitcher_crop pitcher_plant=t:pitcher_plant pitcher_pod=i:pitcher_pod",
  "player_head=i:skull.char plenty_pottery_sherd=i:plenty_pottery_sherd podzol=t:podzol pointed_dripstone=t:pointed_dripstone poisonous_potato=i:poisonous_potato polar_bear_spawn_egg=i:spawn_egg.entity.polar_bear",
  "polished_andesite=t:stone.andesiteSmooth polished_andesite_double_slab=t:double_stone_slab3.andesite.smooth polished_andesite_slab=t:stone_slab3.andesite.smooth polished_andesite_stairs=t:polished_andesite_stairs polished_basalt=t:polished_basalt polished_blackstone=t:polished_blackstone",
  "polished_blackstone_brick_double_slab=t:polished_blackstone_brick_double_slab polished_blackstone_brick_slab=t:polished_blackstone_brick_slab polished_blackstone_brick_stairs=t:polished_blackstone_brick_stairs polished_blackstone_brick_wall=t:polished_blackstone_brick_wall polished_blackstone_bricks=t:polished_blackstone_bricks polished_blackstone_button=t:polished_blackstone_button",
  "polished_blackstone_double_slab=t:polished_blackstone_double_slab polished_blackstone_pressure_plate=t:polished_blackstone_pressure_plate polished_blackstone_slab=t:polished_blackstone_slab polished_blackstone_stairs=t:polished_blackstone_stairs polished_blackstone_wall=t:polished_blackstone_wall polished_cinnabar=t:polished_cinnabar",
  "polished_cinnabar_double_slab=t:polished_cinnabar_double_slab polished_cinnabar_slab=t:polished_cinnabar_slab polished_cinnabar_stairs=t:polished_cinnabar_stairs polished_cinnabar_wall=t:polished_cinnabar_wall polished_deepslate=t:polished_deepslate polished_deepslate_double_slab=t:polished_deepslate_double_slab",
  "polished_deepslate_slab=t:polished_deepslate_slab polished_deepslate_stairs=t:polished_deepslate_stairs polished_deepslate_wall=t:polished_deepslate_wall polished_diorite=t:stone.dioriteSmooth polished_diorite_double_slab=t:double_stone_slab3.diorite.smooth polished_diorite_slab=t:stone_slab3.diorite.smooth",
  "polished_diorite_stairs=t:polished_diorite_stairs polished_granite=t:stone.graniteSmooth polished_granite_double_slab=t:double_stone_slab3.granite.smooth polished_granite_slab=t:stone_slab3.granite.smooth polished_granite_stairs=t:polished_granite_stairs polished_sulfur=t:polished_sulfur",
  "polished_sulfur_double_slab=t:polished_sulfur_double_slab polished_sulfur_slab=t:polished_sulfur_slab polished_sulfur_stairs=t:polished_sulfur_stairs polished_sulfur_wall=t:polished_sulfur_wall polished_tuff=t:polished_tuff polished_tuff_double_slab=t:polished_tuff_double_slab",
  "polished_tuff_slab=t:polished_tuff_slab polished_tuff_stairs=t:polished_tuff_stairs polished_tuff_wall=t:polished_tuff_wall popped_chorus_fruit=i:chorus_fruit_popped poppy=t:red_flower.poppy porkchop=i:porkchop",
  "portal=t:portal potato=i:potato potatoes=t:potatoes potent_sulfur=t:potent_sulfur powder_snow=t:powder_snow powder_snow_bucket=i:bucketPowderSnow",
  "powered_comparator=t:powered_comparator powered_rail=t:golden_rail powered_repeater=t:powered_repeater prismarine=t:prismarine.rough prismarine_brick_double_slab=t:double_stone_slab2.prismarine.bricks prismarine_brick_slab=t:stone_slab2.prismarine.bricks",
  "prismarine_brick_stairs=t:prismarine_bricks_stairs prismarine_bricks=t:prismarine.bricks prismarine_bricks_stairs=t:prismarine_bricks_stairs prismarine_crystals=i:prismarine_crystals prismarine_shard=i:prismarine_shard prismarine_slab=t:stone_slab2.prismarine.rough",
  "prismarine_stairs=t:prismarine_stairs prismarine_wall=t:cobblestone_wall.prismarine prize_pottery_sherd=i:prize_pottery_sherd pufferfish=i:pufferfish pufferfish_bucket=i:bucketPuffer pufferfish_spawn_egg=i:spawn_egg.entity.pufferfish",
  "pumpkin=t:pumpkin pumpkin_pie=i:pumpkin_pie pumpkin_seeds=i:pumpkin_seeds pumpkin_stem=t:pumpkin_stem purple_banner=i:banner.purple purple_bed=i:bed.purple",
  "purple_candle=t:purple_candle purple_candle_cake=t:purple_candle_cake purple_carpet=t:carpet.purple purple_concrete=t:concrete.purple purple_concrete_powder=t:concretePowder.purple purple_dye=i:dye.purple",
  "purple_glazed_terracotta=t:glazedTerracottaPurple purple_harness=i:purple_harness purple_shulker_box=t:shulkerBoxPurple purple_stained_glass=t:stained_glass.purple purple_stained_glass_pane=t:stained_glass_pane.purple purple_terracotta=t:stained_hardened_clay.purple",
  "purple_wool=t:wool.purple purpur_block=t:purpur_block.default purpur_double_slab=t:double_stone_slab2.purpur purpur_pillar=t:purpur_block.lines purpur_slab=t:stone_slab2.purpur purpur_stairs=t:purpur_stairs",
  "quartz=i:quartz quartz_block=t:quartz_block quartz_bricks=t:quartz_bricks quartz_ore=t:quartz_ore quartz_pillar=t:quartz_block.lines quartz_slab=t:stone_slab.quartz",
  "quartz_stairs=t:quartz_stairs rabbit=i:rabbit rabbit_foot=i:rabbit_foot rabbit_hide=i:rabbit_hide rabbit_spawn_egg=i:spawn_egg.entity.rabbit rabbit_stew=i:rabbit_stew",
  "rail=t:rail raiser_armor_trim_smithing_template=i:raiser_armor_trim_smithing_template ravager_spawn_egg=i:spawn_egg.entity.ravager raw_copper=i:raw_copper raw_copper_block=t:raw_copper_block raw_gold=i:raw_gold",
  "raw_gold_block=t:raw_gold_block raw_iron=i:raw_iron raw_iron_block=t:raw_iron_block recovery_compass=i:recovery_compass red_banner=i:banner.red red_bed=i:bed.red",
  "red_candle=t:red_candle red_candle_cake=t:red_candle_cake red_carpet=t:carpet.red red_concrete=t:concrete.red red_concrete_powder=t:concretePowder.red red_dye=i:dye.red",
  "red_glazed_terracotta=t:glazedTerracottaRed red_harness=i:red_harness red_mushroom=t:red_mushroom red_mushroom_block=t:red_mushroom_block red_nether_brick=t:red_nether_brick red_nether_brick_double_slab=t:double_stone_slab2.red_nether_brick",
  "red_nether_brick_slab=t:stone_slab2.red_nether_brick red_nether_brick_stairs=t:red_nether_brick_stairs red_nether_brick_wall=t:cobblestone_wall.red_nether_brick red_nether_bricks=t:red_nether_brick red_sand=t:sand.red red_sandstone=t:red_sandstone",
  "red_sandstone_slab=t:stone_slab2.red_sandstone red_sandstone_stairs=t:red_sandstone_stairs red_sandstone_wall=t:cobblestone_wall.red_sandstone red_shulker_box=t:shulkerBoxRed red_stained_glass=t:stained_glass.red red_stained_glass_pane=t:stained_glass_pane.red",
  "red_terracotta=t:stained_hardened_clay.red red_tulip=t:red_flower.tulipRed red_wool=t:wool.red redstone=i:redstone redstone_block=t:redstone_block redstone_lamp=t:redstone_lamp",
  "redstone_ore=t:redstone_ore redstone_torch=t:redstone_torch redstone_wire=t:redstone_wire reeds=i:reeds reinforced_deepslate=t:reinforced_deepslate repeater=i:repeater",
  "repeating_command_block=t:repeating_command_block resin_block=t:resin_block resin_brick=i:resin_brick resin_brick_double_slab=t:resin_brick_double_slab resin_brick_slab=t:resin_brick_slab resin_brick_stairs=t:resin_brick_stairs",
  "resin_brick_wall=t:resin_brick_wall resin_bricks=t:resin_bricks resin_clump=t:resin_clump respawn_anchor=t:respawn_anchor rib_armor_trim_smithing_template=i:rib_armor_trim_smithing_template rooted_dirt=t:dirt_with_roots",
  "rose_bush=t:double_plant.rose rotten_flesh=i:rotten_flesh saddle=i:saddle salmon=i:salmon salmon_bucket=i:bucketSalmon salmon_spawn_egg=i:spawn_egg.entity.salmon",
  "sand=t:sand sandstone=t:sandstone sandstone_slab=t:stone_slab.sand sandstone_stairs=t:sandstone_stairs sandstone_wall=t:cobblestone_wall.sandstone scaffolding=t:scaffolding",
  "scrape_pottery_sherd=i:scrape_pottery_sherd sculk=t:sculk sculk_catalyst=t:sculk_catalyst sculk_sensor=t:sculk_sensor sculk_shrieker=t:sculk_shrieker sculk_vein=t:sculk_vein",
  "sea_lantern=t:seaLantern sea_pickle=t:sea_pickle seagrass=t:seagrass.seagrass sentry_armor_trim_smithing_template=i:sentry_armor_trim_smithing_template shaper_armor_trim_smithing_template=i:shaper_armor_trim_smithing_template sheaf_pottery_sherd=i:sheaf_pottery_sherd",
  "shears=i:shears sheep_spawn_egg=i:spawn_egg.entity.sheep shelter_pottery_sherd=i:shelter_pottery_sherd shield=i:shield short_dry_grass=t:short_dry_grass short_grass=t:tallgrass",
  "shroomlight=t:shroomlight shulker_box=t:shulkerBox shulker_shell=i:shulker_shell shulker_spawn_egg=i:spawn_egg.entity.shulker sign=i:sign silence_armor_trim_smithing_template=i:silence_armor_trim_smithing_template",
  "silverfish_spawn_egg=i:spawn_egg.entity.silverfish skeleton_horse_spawn_egg=i:spawn_egg.entity.skeleton_horse skeleton_skull=i:skull.skeleton skeleton_spawn_egg=i:spawn_egg.entity.skeleton skull_banner_pattern=i:skull_banner_pattern skull_pottery_sherd=i:skull_pottery_sherd",
  "slime=t:slime slime_ball=i:slime_ball slime_block=t:slime slime_spawn_egg=i:spawn_egg.entity.slime small_amethyst_bud=t:small_amethyst_bud small_dripleaf=t:small_dripleaf_block",
  "small_dripleaf_block=t:small_dripleaf_block smithing_table=t:smithing_table smoker=t:smoker smooth_basalt=t:smooth_basalt smooth_quartz_block=t:quartz_block.smooth smooth_quartz_double_slab=t:double_stone_slab4.smooth_quartz",
  "smooth_quartz_slab=t:stone_slab4.smooth_quartz smooth_quartz_stairs=t:smooth_quartz_stairs smooth_red_sandstone=t:red_sandstone.smooth smooth_red_sandstone_double_slab=t:double_stone_slab3.red_sandstone.smooth smooth_red_sandstone_slab=t:stone_slab3.red_sandstone.smooth smooth_red_sandstone_stairs=t:smooth_red_sandstone_stairs",
  "smooth_sandstone=t:sandstone.smooth smooth_sandstone_double_slab=t:double_stone_slab2.sandstone.smooth smooth_sandstone_slab=t:stone_slab2.sandstone.smooth smooth_sandstone_stairs=t:smooth_sandstone_stairs smooth_stone=t:smooth_stone smooth_stone_slab=t:stone_slab.stone",
  "sniffer_egg=t:sniffer_egg sniffer_spawn_egg=i:spawn_egg.entity.sniffer snort_pottery_sherd=i:snort_pottery_sherd snout_armor_trim_smithing_template=i:snout_armor_trim_smithing_template snow=t:snow snow_block=t:snow",
  "snow_golem_spawn_egg=i:spawn_egg.entity.snow_golem snow_layer=t:snow_layer snowball=i:snowball soul_campfire=t:soul_campfire soul_fire=t:soul_fire soul_lantern=t:soul_lantern",
  "soul_sand=t:soul_sand soul_soil=t:soul_soil soul_torch=t:soul_torch spider_eye=i:spider_eye spider_spawn_egg=i:spawn_egg.entity.spider spire_armor_trim_smithing_template=i:spire_armor_trim_smithing_template",
  "sponge=t:sponge.dry spore_blossom=t:spore_blossom spruce_boat=i:boat.spruce spruce_button=t:spruce_button spruce_chest_boat=i:chest_boat.spruce spruce_door=i:spruce_door",
  "spruce_double_slab=t:double_wooden_slab.spruce spruce_fence=t:spruceFence spruce_fence_gate=t:spruce_fence_gate spruce_hanging_sign=i:spruce_hanging_sign spruce_leaves=t:leaves.spruce spruce_log=t:log.spruce",
  "spruce_planks=t:planks.spruce spruce_pressure_plate=t:spruce_pressure_plate spruce_sapling=t:sapling.spruce spruce_shelf=t:spruce_shelf spruce_sign=i:spruce_sign spruce_slab=t:wooden_slab.spruce",
  "spruce_stairs=t:spruce_stairs spruce_standing_sign=t:spruce_standing_sign spruce_trapdoor=t:spruce_trapdoor spruce_wall_sign=t:spruce_wall_sign spruce_wood=t:wood.spruce spyglass=i:spyglass",
  "squid_spawn_egg=i:spawn_egg.entity.squid standing_banner=t:standing_banner standing_sign=t:standing_sign stick=i:stick sticky_piston=t:sticky_piston sticky_piston_arm_collision=t:sticky_piston_arm_collision",
  "stone=t:stone.stone stone_axe=i:stone_axe stone_brick=t:stonebrick stone_brick_slab=t:stone_slab.smoothStoneBrick stone_brick_stairs=t:stone_brick_stairs stone_brick_wall=t:cobblestone_wall.stone_brick",
  "stone_bricks=t:stonebrick stone_button=t:stone_button stone_hoe=i:stone_hoe stone_pickaxe=i:stone_pickaxe stone_pressure_plate=t:stone_pressure_plate stone_shovel=i:stone_shovel",
  "stone_slab=t:stone_slab stone_spear=i:stone_spear stone_stairs=t:stone_stairs stone_sword=i:stone_sword stonecutter=t:stonecutter stonecutter_block=t:stonecutter_block",
  "stray_spawn_egg=i:spawn_egg.entity.stray strider_spawn_egg=i:spawn_egg.entity.strider string=i:string stripped_acacia_log=t:stripped_acacia_log stripped_acacia_wood=t:wood.stripped.acacia stripped_bamboo_block=t:stripped_bamboo_block",
  "stripped_birch_log=t:stripped_birch_log stripped_birch_wood=t:wood.stripped.birch stripped_cherry_log=t:stripped_cherry_log stripped_cherry_wood=t:stripped_cherry_wood stripped_crimson_hyphae=t:stripped_crimson_hyphae stripped_crimson_stem=t:stripped_crimson_stem",
  "stripped_dark_oak_log=t:stripped_dark_oak_log stripped_dark_oak_wood=t:wood.stripped.dark_oak stripped_jungle_log=t:stripped_jungle_log stripped_jungle_wood=t:wood.stripped.jungle stripped_mangrove_log=t:stripped_mangrove_log stripped_mangrove_wood=t:stripped_mangrove_wood",
  "stripped_oak_log=t:stripped_oak_log stripped_oak_wood=t:wood.stripped.oak stripped_pale_oak_log=t:stripped_pale_oak_log stripped_pale_oak_wood=t:stripped_pale_oak_wood stripped_spruce_log=t:stripped_spruce_log stripped_spruce_wood=t:wood.stripped.spruce",
  "stripped_warped_hyphae=t:stripped_warped_hyphae stripped_warped_stem=t:stripped_warped_stem structure_block=t:structure_block structure_void=t:structure_void sugar=i:sugar sugar_cane=i:reeds",
  "sulfur=t:sulfur sulfur_brick_double_slab=t:sulfur_brick_double_slab sulfur_brick_slab=t:sulfur_brick_slab sulfur_brick_stairs=t:sulfur_brick_stairs sulfur_brick_wall=t:sulfur_brick_wall sulfur_bricks=t:sulfur_bricks",
  "sulfur_cube_spawn_egg=i:spawn_egg.entity.sulfur_cube sulfur_double_slab=t:sulfur_double_slab sulfur_slab=t:sulfur_slab sulfur_spike=t:sulfur_spike sulfur_stairs=t:sulfur_stairs sulfur_wall=t:sulfur_wall",
  "sunflower=t:double_plant.sunflower suspicious_gravel=t:suspicious_gravel suspicious_sand=t:suspicious_sand suspicious_stew=i:suspicious_stew sweet_berries=i:sweet_berries sweet_berry_bush=t:sweet_berry_bush",
  "tadpole_bucket=i:bucketTadpole tadpole_spawn_egg=i:spawn_egg.entity.tadpole tall_dry_grass=t:tall_dry_grass tall_grass=t:double_plant.grass target=t:target terracotta=t:hardened_clay",
  "tide_armor_trim_smithing_template=i:tide_armor_trim_smithing_template tinted_glass=t:tinted_glass tipped_arrow=i:tipped_arrow tnt=t:tnt tnt_minecart=i:tnt_minecart torch=t:torch",
  "torchflower=t:torchflower torchflower_crop=t:torchflower_crop torchflower_seeds=i:torchflower_seeds totem_of_undying=i:totem trader_llama_spawn_egg=i:spawn_egg.entity.trader_llama trapdoor=t:trapdoor",
  "trapped_chest=t:trapped_chest trial_key=i:trial_key trial_spawner=t:trial_spawner trident=i:trident trip_wire=t:tripWire tripwire_hook=t:tripwire_hook",
  "tropical_fish=i:clownfish tropical_fish_bucket=i:bucketTropical tropical_fish_spawn_egg=i:spawn_egg.entity.tropicalfish tube_coral=t:coral.blue tube_coral_block=t:coral_block.blue tube_coral_fan=t:coral_fan.blue_fan",
  "tube_coral_wall_fan=t:tube_coral_wall_fan tuff=t:tuff tuff_brick_double_slab=t:tuff_brick_double_slab tuff_brick_slab=t:tuff_brick_slab tuff_brick_stairs=t:tuff_brick_stairs tuff_brick_wall=t:tuff_brick_wall",
  "tuff_bricks=t:tuff_bricks tuff_double_slab=t:tuff_double_slab tuff_slab=t:tuff_slab tuff_stairs=t:tuff_stairs tuff_wall=t:tuff_wall turtle_egg=t:turtle_egg",
  "turtle_helmet=i:turtle_helmet turtle_scute=i:turtle_shell_piece turtle_spawn_egg=i:spawn_egg.entity.turtle twisting_vines=t:twisting_vines unknown=t:unknown unlit_redstone_torch=t:unlit_redstone_torch",
  "unpowered_comparator=t:unpowered_comparator unpowered_repeater=t:unpowered_repeater vault=t:vault verdant_froglight=t:verdant_froglight vex_armor_trim_smithing_template=i:vex_armor_trim_smithing_template vex_spawn_egg=i:spawn_egg.entity.vex",
  "villager_spawn_egg=i:spawn_egg.entity.villager vindicator_spawn_egg=i:spawn_egg.entity.vindicator vine=t:vine wall_banner=t:wall_banner wall_sign=t:wall_sign wandering_trader_spawn_egg=i:spawn_egg.entity.wandering_trader",
  "ward_armor_trim_smithing_template=i:ward_armor_trim_smithing_template warden_spawn_egg=i:spawn_egg.entity.warden warped_button=t:warped_button warped_door=i:warped_door warped_double_slab=t:warped_double_slab warped_fence=t:warped_fence",
  "warped_fence_gate=t:warped_fence_gate warped_fungus=t:warped_fungus warped_fungus_on_a_stick=i:warped_fungus_on_a_stick warped_hanging_sign=i:warped_hanging_sign warped_hyphae=t:warped_hyphae warped_nylium=t:warped_nylium",
  "warped_planks=t:warped_planks warped_pressure_plate=t:warped_pressure_plate warped_roots=t:warped_roots.warpedRoots warped_shelf=t:warped_shelf warped_sign=i:warped_sign warped_slab=t:warped_slab",
  "warped_stairs=t:warped_stairs warped_standing_sign=t:warped_standing_sign warped_stem=t:warped_stem warped_trapdoor=t:warped_trapdoor warped_wall_sign=t:warped_wall_sign warped_wart_block=t:warped_wart_block",
  "water=t:water water_bucket=i:bucketWater waterlily=t:waterlily waxed_chiseled_copper=t:waxed_chiseled_copper waxed_copper=t:waxed_copper waxed_copper_bars=t:waxed_copper_bars",
  "waxed_copper_bulb=t:waxed_copper_bulb waxed_copper_chain=t:waxed_copper_chain waxed_copper_chest=t:waxed_copper_chest waxed_copper_door=i:waxed_copper_door waxed_copper_golem_statue=t:waxed_copper_golem_statue waxed_copper_grate=t:waxed_copper_grate",
  "waxed_copper_lantern=t:waxed_copper_lantern waxed_copper_trapdoor=t:waxed_copper_trapdoor waxed_cut_copper=t:waxed_cut_copper waxed_cut_copper_slab=t:waxed_cut_copper_slab waxed_cut_copper_stairs=t:waxed_cut_copper_stairs waxed_double_cut_copper_slab=t:waxed_double_cut_copper_slab",
  "waxed_exposed_chiseled_copper=t:waxed_exposed_chiseled_copper waxed_exposed_copper=t:waxed_exposed_copper waxed_exposed_copper_bars=t:waxed_exposed_copper_bars waxed_exposed_copper_bulb=t:waxed_exposed_copper_bulb waxed_exposed_copper_chain=t:waxed_exposed_copper_chain waxed_exposed_copper_chest=t:waxed_exposed_copper_chest",
  "waxed_exposed_copper_door=i:waxed_exposed_copper_door waxed_exposed_copper_golem_statue=t:waxed_exposed_copper_golem_statue waxed_exposed_copper_grate=t:waxed_exposed_copper_grate waxed_exposed_copper_lantern=t:waxed_exposed_copper_lantern waxed_exposed_copper_trapdoor=t:waxed_exposed_copper_trapdoor waxed_exposed_cut_copper=t:waxed_exposed_cut_copper",
  "waxed_exposed_cut_copper_slab=t:waxed_exposed_cut_copper_slab waxed_exposed_cut_copper_stairs=t:waxed_exposed_cut_copper_stairs waxed_exposed_double_cut_copper_slab=t:waxed_exposed_double_cut_copper_slab waxed_exposed_lightning_rod=t:waxed_exposed_lightning_rod waxed_lightning_rod=t:waxed_lightning_rod waxed_oxidized_chiseled_copper=t:waxed_oxidized_chiseled_copper",
  "waxed_oxidized_copper=t:waxed_oxidized_copper waxed_oxidized_copper_bars=t:waxed_oxidized_copper_bars waxed_oxidized_copper_bulb=t:waxed_oxidized_copper_bulb waxed_oxidized_copper_chain=t:waxed_oxidized_copper_chain waxed_oxidized_copper_chest=t:waxed_oxidized_copper_chest waxed_oxidized_copper_door=i:waxed_oxidized_copper_door",
  "waxed_oxidized_copper_golem_statue=t:waxed_oxidized_copper_golem_statue waxed_oxidized_copper_grate=t:waxed_oxidized_copper_grate waxed_oxidized_copper_lantern=t:waxed_oxidized_copper_lantern waxed_oxidized_copper_trapdoor=t:waxed_oxidized_copper_trapdoor waxed_oxidized_cut_copper=t:waxed_oxidized_cut_copper waxed_oxidized_cut_copper_slab=t:waxed_oxidized_cut_copper_slab",
  "waxed_oxidized_cut_copper_stairs=t:waxed_oxidized_cut_copper_stairs waxed_oxidized_double_cut_copper_slab=t:waxed_oxidized_double_cut_copper_slab waxed_oxidized_lightning_rod=t:waxed_oxidized_lightning_rod waxed_weathered_chiseled_copper=t:waxed_weathered_chiseled_copper waxed_weathered_copper=t:waxed_weathered_copper waxed_weathered_copper_bars=t:waxed_weathered_copper_bars",
  "waxed_weathered_copper_bulb=t:waxed_weathered_copper_bulb waxed_weathered_copper_chain=t:waxed_weathered_copper_chain waxed_weathered_copper_chest=t:waxed_weathered_copper_chest waxed_weathered_copper_door=i:waxed_weathered_copper_door waxed_weathered_copper_golem_statue=t:waxed_weathered_copper_golem_statue waxed_weathered_copper_grate=t:waxed_weathered_copper_grate",
  "waxed_weathered_copper_lantern=t:waxed_weathered_copper_lantern waxed_weathered_copper_trapdoor=t:waxed_weathered_copper_trapdoor waxed_weathered_cut_copper=t:waxed_weathered_cut_copper waxed_weathered_cut_copper_slab=t:waxed_weathered_cut_copper_slab waxed_weathered_cut_copper_stairs=t:waxed_weathered_cut_copper_stairs waxed_weathered_double_cut_copper_slab=t:waxed_weathered_double_cut_copper_slab",
  "waxed_weathered_lightning_rod=t:waxed_weathered_lightning_rod wayfinder_armor_trim_smithing_template=i:wayfinder_armor_trim_smithing_template weathered_chiseled_copper=t:weathered_chiseled_copper weathered_copper=t:weathered_copper weathered_copper_bars=t:weathered_copper_bars weathered_copper_bulb=t:weathered_copper_bulb",
  "weathered_copper_chain=t:weathered_copper_chain weathered_copper_chest=t:weathered_copper_chest weathered_copper_door=i:weathered_copper_door weathered_copper_golem_statue=t:weathered_copper_golem_statue weathered_copper_grate=t:weathered_copper_grate weathered_copper_lantern=t:weathered_copper_lantern",
  "weathered_copper_trapdoor=t:weathered_copper_trapdoor weathered_cut_copper=t:weathered_cut_copper weathered_cut_copper_slab=t:weathered_cut_copper_slab weathered_cut_copper_stairs=t:weathered_cut_copper_stairs weathered_double_cut_copper_slab=t:weathered_double_cut_copper_slab weathered_lightning_rod=t:weathered_lightning_rod",
  "web=t:web weeping_vines=t:weeping_vines wet_sponge=t:sponge.wet wheat=i:wheat wheat_seeds=i:wheat_seeds white_banner=i:banner.white",
  "white_bed=i:bed.white white_candle=t:white_candle white_candle_cake=t:white_candle_cake white_carpet=t:carpet.white white_concrete=t:concrete.white white_concrete_powder=t:concretePowder.white",
  "white_dye=i:dye.white white_glazed_terracotta=t:glazedTerracottaWhite white_harness=i:white_harness white_shulker_box=t:shulkerBoxWhite white_stained_glass=t:stained_glass.white white_stained_glass_pane=t:stained_glass_pane.white",
  "white_terracotta=t:stained_hardened_clay.white white_tulip=t:red_flower.tulipWhite white_wool=t:wool.white wild_armor_trim_smithing_template=i:wild_armor_trim_smithing_template wildflowers=t:wildflowers wind_charge=i:wind_charge",
  "witch_spawn_egg=i:spawn_egg.entity.witch wither_rose=t:wither_rose wither_skeleton_skull=i:skull.wither wither_skeleton_spawn_egg=i:spawn_egg.entity.wither_skeleton wither_spawn_egg=i:spawn_egg.entity.wither wolf_armor=i:wolf_armor",
  "wolf_spawn_egg=i:spawn_egg.entity.wolf wooden_axe=i:wooden_axe wooden_button=t:wooden_button wooden_door=i:wooden_door wooden_hoe=i:wooden_hoe wooden_pickaxe=i:wooden_pickaxe",
  "wooden_pressure_plate=t:wooden_pressure_plate wooden_shovel=i:wooden_shovel wooden_spear=i:wooden_spear wooden_sword=i:wooden_sword writable_book=i:writable_book written_book=i:written_book",
  "yellow_banner=i:banner.yellow yellow_bed=i:bed.yellow yellow_candle=t:yellow_candle yellow_candle_cake=t:yellow_candle_cake yellow_carpet=t:carpet.yellow yellow_concrete=t:concrete.yellow",
  "yellow_concrete_powder=t:concretePowder.yellow yellow_dye=i:dye.yellow yellow_glazed_terracotta=t:glazedTerracottaYellow yellow_harness=i:yellow_harness yellow_shulker_box=t:shulkerBoxYellow yellow_stained_glass=t:stained_glass.yellow",
  "yellow_stained_glass_pane=t:stained_glass_pane.yellow yellow_terracotta=t:stained_hardened_clay.yellow yellow_wool=t:wool.yellow zoglin_spawn_egg=i:spawn_egg.entity.zoglin zombie_head=i:skull.zombie zombie_horse_spawn_egg=i:spawn_egg.entity.zombie_horse",
  "zombie_nautilus_spawn_egg=i:spawn_egg.entity.zombie_nautilus zombie_spawn_egg=i:spawn_egg.entity.zombie zombie_villager_spawn_egg=i:spawn_egg.entity.zombie_villager zombified_piglin_spawn_egg=i:spawn_egg.entity.zombie_pigman",
];

const HARITA = new Map();
for (const satir of HAM) {
  for (const parca of satir.split(" ")) {
    const i = parca.indexOf("=");
    if (i < 0) continue;
    const id = parca.slice(0, i), kod = parca.slice(i + 1);
    HARITA.set(id,
      kod.startsWith("t:") ? `tile.${kod.slice(2)}.name`
      : kod.startsWith("i:") ? `item.${kod.slice(2)}.name`
      : kod.slice(1));
  }
}

// Dogrulanmis dil anahtari. Yoksa undefined doner; cagiran duz metne duser.
export function adAnahtari(typeId) {
  return HARITA.get(String(typeId).replace(/^minecraft:/, ""));
}
export const ADET = HARITA.size;
