// ============ ESYA IKON HARITASI ============
// ikon_guncelle.py tarafindan Mojang'in resmi vanilla resource pack
// verisinden uretilmistir. ELLE DUZENLEME: uretici yeniden calisinca
// ustune yazar; kalici degisiklik icin icons.js icindeki OZEL tablosunu
// ya da ikon_guncelle.py icindeki ELLE tablosunu kullan.
//
// Kaynak: v1.21.90.3 (1395 esya) + main (+186 yeni esya).
// Buradaki her yol, kaynak surumun kendi texture tanimlarinda GECIYOR diye
// dogrulanmistir; dogrulanamayan yol haritaya hic yazilmaz (icons.js soru
// isareti gorseline duser, oyunda mor-siyah kare cikmaz).
//
// Bicim: "<esya_id>=<yol>" ciftleri. "i:" = textures/items/, "b:" = textures/blocks/

const HARITA_HAM = [
  "acacia_boat=i:boat_acacia acacia_button=b:planks_acacia acacia_door=i:door_acacia",
  "acacia_fence=b:planks_acacia acacia_fence_gate=b:planks_acacia acacia_hanging_sign=b:planks_acacia",
  "acacia_leaves=b:leaves_acacia acacia_log=b:log_acacia acacia_planks=b:planks_acacia",
  "acacia_pressure_plate=b:planks_acacia acacia_sapling=b:sapling_acacia acacia_sign=i:sign_acacia",
  "acacia_slab=b:planks_acacia acacia_stairs=b:planks_acacia acacia_wood=b:log_acacia",
  "activator_rail=b:rail_activator allay_spawn_egg=i:spawn_eggs/spawn_egg_allay allium=b:flower_allium",
  "allow=b:build_allow ancient_debris=b:ancient_debris_top andesite=b:stone_andesite",
  "andesite_slab=b:stone_andesite andesite_stairs=b:stone_andesite andesite_wall=b:stone_andesite",
  "anvil=b:anvil_base armadillo_spawn_egg=i:spawn_eggs/spawn_egg_armadillo",
  "axolotl_bucket=i:bucket_axolotl axolotl_spawn_egg=i:spawn_eggs/spawn_egg_axolotl",
  "azalea=b:azalea_side azalea_leaves_flowered=b:azalea_leaves_flowers azure_bluet=b:flower_houstonia",
  "baked_potato=i:potato_baked bamboo=b:bamboo_leaf bamboo_button=b:bamboo_planks",
  "bamboo_hanging_sign=b:bamboo_planks bamboo_mosaic_slab=b:bamboo_mosaic",
  "bamboo_mosaic_stairs=b:bamboo_mosaic bamboo_pressure_plate=b:bamboo_planks",
  "bamboo_slab=b:bamboo_planks bamboo_stairs=b:bamboo_planks banner=i:banner_pattern",
  "barrel=i:market_sandik basalt=b:basalt_side bat_spawn_egg=i:spawn_eggs/spawn_egg_bat beacon=b:glass",
  "bed=i:bed_white bee_nest=b:bee_nest_top bee_spawn_egg=i:spawn_eggs/spawn_egg_bee beef=i:beef_raw",
  "beehive=b:beehive_top beetroot_seeds=i:seeds_beetroot bell=b:bell_top",
  "big_dripleaf=b:big_dripleaf_side2 birch_boat=i:boat_birch birch_button=b:planks_birch",
  "birch_door=i:door_birch birch_fence=b:planks_birch birch_fence_gate=b:planks_birch",
  "birch_hanging_sign=b:planks_birch birch_leaves=b:leaves_birch birch_log=b:log_birch",
  "birch_planks=b:planks_birch birch_pressure_plate=b:planks_birch birch_sapling=b:sapling_birch",
  "birch_sign=i:sign_birch birch_slab=b:planks_birch birch_stairs=b:planks_birch birch_wood=b:log_birch",
  "black_bundle=i:bundle_black black_candle=b:candles/black_candle black_carpet=b:wool_colored_black",
  "black_concrete=b:concrete_black black_concrete_powder=b:concrete_powder_black",
  "black_cushion=i:candles/black_candle black_dye=i:dye_powder_black",
  "black_glazed_terracotta=b:glazed_terracotta_black black_harness=i:harness/harness_black",
  "black_shulker_box=b:shulker_top_black black_stained_glass=b:glass_black",
  "black_stained_glass_pane=b:glass_black black_terracotta=b:hardened_clay_stained_black",
  "black_wool=b:wool_colored_black black_wool_double_slab=b:wool_colored_black",
  "black_wool_slab=b:wool_colored_black black_wool_stairs=b:wool_colored_black",
  "blackstone_slab=b:blackstone blackstone_stairs=b:blackstone blackstone_wall=b:blackstone",
  "blast_furnace=b:blast_furnace_top blaze_spawn_egg=i:spawn_eggs/spawn_egg_blaze",
  "blue_bundle=i:bundle_blue blue_candle=b:candles/blue_candle blue_carpet=b:wool_colored_blue",
  "blue_concrete=b:concrete_blue blue_concrete_powder=b:concrete_powder_blue blue_cushion=b:blue_ice",
  "blue_dye=i:dye_powder_blue blue_glazed_terracotta=b:glazed_terracotta_blue",
  "blue_harness=i:harness/harness_blue blue_orchid=b:flower_blue_orchid",
  "blue_shulker_box=b:shulker_top_blue blue_stained_glass=b:glass_blue",
  "blue_stained_glass_pane=b:glass_blue blue_terracotta=b:hardened_clay_stained_blue",
  "blue_wool=b:wool_colored_blue blue_wool_double_slab=b:wool_colored_blue",
  "blue_wool_slab=b:wool_colored_blue blue_wool_stairs=b:wool_colored_blue",
  "bogged_spawn_egg=i:spawn_eggs/spawn_egg_bogged bone_block=b:bone_block_side",
  "bone_meal=i:dye_powder_white book=i:book_normal border_block=b:border bow=i:bow_standby",
  "brain_coral=b:coral_plant_pink brain_coral_block=b:coral_pink brain_coral_fan=b:coral_fan_pink",
  "breeze_spawn_egg=i:spawn_eggs/spawn_egg_breeze brick_block=b:brick brick_slab=b:brick",
  "brick_stairs=b:brick brick_wall=b:brick brown_bundle=i:bundle_brown",
  "brown_candle=b:candles/brown_candle brown_carpet=b:wool_colored_brown",
  "brown_concrete=b:concrete_brown brown_concrete_powder=b:concrete_powder_brown",
  "brown_cushion=i:candles/brown_candle brown_dye=i:dye_powder_brown",
  "brown_glazed_terracotta=b:glazed_terracotta_brown brown_harness=i:harness/harness_brown",
  "brown_mushroom=b:mushroom_brown brown_mushroom_block=b:mushroom_block_inside",
  "brown_shulker_box=b:shulker_top_brown brown_stained_glass=b:glass_brown",
  "brown_stained_glass_pane=b:glass_brown brown_terracotta=b:hardened_clay_stained_brown",
  "brown_wool=b:wool_colored_brown brown_wool_double_slab=b:wool_colored_brown",
  "brown_wool_slab=b:wool_colored_brown brown_wool_stairs=b:wool_colored_brown",
  "bubble_coral=b:coral_plant_purple bubble_coral_block=b:coral_purple",
  "bubble_coral_fan=b:coral_fan_purple bucket=i:bucket_empty cactus=b:cactus_side",
  "calibrated_sculk_sensor=b:calibrated_sculk_sensor_top",
  "camel_husk_spawn_egg=i:spawn_eggs/spawn_egg_camel_husk camel_spawn_egg=i:spawn_eggs/spawn_egg_camel",
  "candle=b:candles/candle cartography_table=b:cartography_table_top carved_pumpkin=b:pumpkin_top",
  "cat_spawn_egg=i:spawn_eggs/spawn_egg_cat cave_spider_spawn_egg=i:spawn_eggs/spawn_egg_cave_spider",
  "chain_command_block=b:chain_command_block_conditional_mipmap cherry_button=b:cherry_planks",
  "cherry_fence=b:cherry_planks cherry_fence_gate=b:cherry_planks cherry_hanging_sign=b:cherry_planks",
  "cherry_log=b:cherry_log_side cherry_pressure_plate=b:cherry_planks cherry_slab=b:cherry_planks",
  "cherry_stairs=b:cherry_planks cherry_wood=b:cherry_log_side chest=i:market_sandik",
  "chest_minecart=i:minecart_chest chicken=i:chicken_raw",
  "chicken_spawn_egg=i:spawn_eggs/spawn_egg_chicken chipped_anvil=b:anvil_base",
  "chiseled_bookshelf=b:chiseled_bookshelf_top chiseled_deepslate=b:deepslate/chiseled_deepslate",
  "chiseled_quartz_block=b:quartz_block_chiseled chiseled_red_sandstone=b:red_sandstone_carved",
  "chiseled_sandstone=b:sandstone_carved chiseled_stone_bricks=b:stonebrick_carved",
  "cinnabar_brick_slab=b:cinnabar_bricks cinnabar_brick_stairs=b:cinnabar_bricks",
  "cinnabar_brick_wall=b:cinnabar_bricks cinnabar_slab=b:cinnabar cinnabar_stairs=b:cinnabar",
  "cinnabar_wall=b:cinnabar clock=i:clock_item closed_eyeblossom=b:eyeblossom_dormant",
  "cobbled_deepslate=b:deepslate/cobbled_deepslate cobbled_deepslate_slab=b:deepslate/cobbled_deepslate",
  "cobbled_deepslate_stairs=b:deepslate/cobbled_deepslate",
  "cobbled_deepslate_wall=b:deepslate/cobbled_deepslate cobblestone_slab=b:cobblestone",
  "cobblestone_wall=b:cobblestone cocoa_beans=i:dye_powder_brown cod=i:bucket_cod",
  "cod_bucket=i:bucket_cod cod_spawn_egg=i:spawn_eggs/spawn_egg_cod",
  "command_block=b:command_block_conditional_mipmap command_block_minecart=i:minecart_command_block",
  "compass=i:compass_item composter=b:composter_side conduit=b:conduit_base cooked_beef=i:beef_cooked",
  "cooked_chicken=i:chicken_cooked cooked_cod=i:fish_cooked cooked_mutton=i:mutton_cooked",
  "cooked_porkchop=i:porkchop_cooked cooked_rabbit=i:rabbit_cooked cooked_salmon=i:fish_salmon_cooked",
  "copper_chain=b:copper_chain2 copper_chest=b:copper_chest_inventory_top",
  "copper_golem_spawn_egg=i:spawn_eggs/spawn_egg_copper_golem copper_golem_statue=b:copper_block",
  "copper_nautilus_armor=i:nautilus_armor/copper_nautilus_armor copper_spear=i:spear/copper_spear",
  "cornflower=b:flower_cornflower cow_spawn_egg=i:spawn_eggs/spawn_egg_cow",
  "cracked_deepslate_bricks=b:deepslate/cracked_deepslate_bricks",
  "cracked_deepslate_tiles=b:deepslate/cracked_deepslate_tiles",
  "cracked_stone_bricks=b:stonebrick_cracked crafter=b:crafter_top crafting_table=b:crafting_table_top",
  "creaking_heart=b:creaking_heart_side_inactive creaking_spawn_egg=i:spawn_eggs/spawn_egg_creaking",
  "creeper_head=b:soul_sand creeper_spawn_egg=i:spawn_eggs/spawn_egg_creeper",
  "crimson_button=b:huge_fungus/crimson_planks crimson_fence=b:huge_fungus/crimson_planks",
  "crimson_fence_gate=b:huge_fungus/crimson_planks crimson_hanging_sign=b:huge_fungus/crimson_planks",
  "crimson_hyphae=b:huge_fungus/crimson_log_side crimson_nylium=b:crimson_nylium_top",
  "crimson_planks=b:huge_fungus/crimson_planks crimson_pressure_plate=b:huge_fungus/crimson_planks",
  "crimson_sign=i:sign_crimson crimson_slab=b:huge_fungus/crimson_planks",
  "crimson_stairs=b:huge_fungus/crimson_planks crimson_stem=b:huge_fungus/crimson_log_top",
  "crimson_trapdoor=b:huge_fungus/crimson_trapdoor crossbow=i:crossbow_standby",
  "cut_copper_slab=b:cut_copper cut_copper_stairs=b:cut_copper cut_red_sandstone=b:red_sandstone_smooth",
  "cut_red_sandstone_slab=b:red_sandstone_smooth cut_sandstone=b:sandstone_smooth",
  "cut_sandstone_slab=b:sandstone_smooth cyan_bundle=i:bundle_cyan cyan_candle=b:candles/cyan_candle",
  "cyan_carpet=b:wool_colored_cyan cyan_concrete=b:concrete_cyan",
  "cyan_concrete_powder=b:concrete_powder_cyan cyan_cushion=i:candles/cyan_candle",
  "cyan_dye=i:dye_powder_cyan cyan_glazed_terracotta=b:glazed_terracotta_cyan",
  "cyan_harness=i:harness/harness_cyan cyan_shulker_box=b:shulker_top_cyan",
  "cyan_stained_glass=b:glass_cyan cyan_stained_glass_pane=b:glass_cyan",
  "cyan_terracotta=b:hardened_clay_stained_cyan cyan_wool=b:wool_colored_cyan",
  "cyan_wool_double_slab=b:wool_colored_cyan cyan_wool_slab=b:wool_colored_cyan",
  "cyan_wool_stairs=b:wool_colored_cyan damaged_anvil=b:anvil_base dandelion=b:flower_dandelion",
  "dark_oak_boat=i:boat_darkoak dark_oak_button=b:planks_big_oak dark_oak_door=i:door_dark_oak",
  "dark_oak_fence=b:planks_big_oak dark_oak_fence_gate=b:planks_big_oak",
  "dark_oak_hanging_sign=b:planks_big_oak dark_oak_leaves=b:leaves_big_oak dark_oak_log=b:log_big_oak",
  "dark_oak_planks=b:planks_big_oak dark_oak_pressure_plate=b:planks_big_oak",
  "dark_oak_sapling=b:sapling_roofed_oak dark_oak_sign=i:sign_darkoak dark_oak_slab=b:planks_big_oak",
  "dark_oak_stairs=b:planks_big_oak dark_oak_wood=b:log_big_oak dark_prismarine=b:prismarine_dark",
  "dark_prismarine_slab=b:prismarine_dark dark_prismarine_stairs=b:prismarine_dark",
  "daylight_detector=b:daylight_detector_side dead_brain_coral=b:coral_plant_pink_dead",
  "dead_brain_coral_block=b:coral_pink_dead dead_brain_coral_fan=b:coral_fan_pink_dead",
  "dead_bubble_coral=b:coral_plant_purple_dead dead_bubble_coral_block=b:coral_purple_dead",
  "dead_bubble_coral_fan=b:coral_fan_purple_dead dead_fire_coral=b:coral_plant_red_dead",
  "dead_fire_coral_block=b:coral_red_dead dead_fire_coral_fan=b:coral_fan_red_dead",
  "dead_horn_coral=b:coral_plant_yellow_dead dead_horn_coral_block=b:coral_yellow_dead",
  "dead_horn_coral_fan=b:coral_fan_yellow_dead dead_tube_coral=b:coral_plant_blue_dead",
  "dead_tube_coral_block=b:coral_blue_dead dead_tube_coral_fan=b:coral_fan_blue_dead",
  "decorated_pot=b:decorated_pot_side deepslate=b:deepslate/deepslate",
  "deepslate_brick_slab=b:deepslate/deepslate_bricks",
  "deepslate_brick_stairs=b:deepslate/deepslate_bricks",
  "deepslate_brick_wall=b:deepslate/deepslate_bricks deepslate_bricks=b:deepslate/deepslate_bricks",
  "deepslate_coal_ore=b:deepslate/deepslate_coal_ore",
  "deepslate_copper_ore=b:deepslate/deepslate_copper_ore",
  "deepslate_diamond_ore=b:deepslate/deepslate_diamond_ore",
  "deepslate_emerald_ore=b:deepslate/deepslate_emerald_ore",
  "deepslate_gold_ore=b:deepslate/deepslate_gold_ore deepslate_iron_ore=b:deepslate/deepslate_iron_ore",
  "deepslate_lapis_ore=b:deepslate/deepslate_lapis_ore",
  "deepslate_redstone_ore=b:deepslate/deepslate_redstone_ore",
  "deepslate_tile_slab=b:deepslate/deepslate_tiles deepslate_tile_stairs=b:deepslate/deepslate_tiles",
  "deepslate_tile_wall=b:deepslate/deepslate_tiles deepslate_tiles=b:deepslate/deepslate_tiles",
  "deny=b:build_deny detector_rail=b:rail_detector",
  "diamond_nautilus_armor=i:nautilus_armor/diamond_nautilus_armor diamond_spear=i:spear/diamond_spear",
  "diorite=b:stone_diorite diorite_slab=b:stone_diorite diorite_stairs=b:stone_diorite",
  "diorite_wall=b:stone_diorite dispenser=b:furnace_top",
  "dolphin_spawn_egg=i:spawn_eggs/spawn_egg_dolphin donkey_spawn_egg=i:spawn_eggs/spawn_egg_donkey",
  "dragon_breath=i:dragons_breath dragon_head=b:soul_sand dried_ghast=b:dried_ghast_state_1_top",
  "dried_kelp_block=b:dried_kelp_top dropper=b:furnace_top",
  "drowned_spawn_egg=i:spawn_eggs/spawn_egg_drowned",
  "elder_guardian_spawn_egg=i:spawn_eggs/spawn_egg_elder_guardian empty_map=i:map_empty",
  "enchanted_book=i:book_enchanted enchanted_golden_apple=i:apple_golden",
  "enchanting_table=b:enchanting_table_side end_brick_stairs=b:end_bricks",
  "end_portal_frame=b:endframe_top end_stone_brick_slab=b:end_bricks end_stone_brick_wall=b:end_bricks",
  "ender_chest=i:market_endersandik ender_dragon_spawn_egg=i:spawn_eggs/spawn_egg_ender_dragon",
  "enderman_spawn_egg=i:spawn_eggs/spawn_egg_enderman",
  "endermite_spawn_egg=i:spawn_eggs/spawn_egg_endermite evoker_spawn_egg=i:spawn_eggs/spawn_egg_evoker",
  "exposed_copper_chain=b:exposed_copper_chain2",
  "exposed_copper_chest=b:exposed_copper_chest_inventory_top",
  "exposed_copper_golem_statue=b:exposed_copper exposed_cut_copper_slab=b:exposed_cut_copper",
  "exposed_cut_copper_stairs=b:exposed_cut_copper farmland=b:dirt fence_gate=b:planks_oak",
  "fermented_spider_eye=i:spider_eye_fermented filled_map=i:map_filled fire_charge=i:fireball",
  "fire_coral=b:coral_plant_red fire_coral_block=b:coral_red fire_coral_fan=b:coral_fan_red",
  "firework_rocket=i:fireworks firework_star=i:fireworks_charge fishing_rod=i:fishing_rod_uncast",
  "fletching_table=b:fletcher_table_top flowering_azalea=b:flowering_azalea_side",
  "fox_spawn_egg=i:spawn_eggs/spawn_egg_fox frame=b:itemframe_background frog_spawn=b:frogspawn",
  "frog_spawn_egg=i:spawn_eggs/spawn_egg_frog frosted_ice=b:frosted_ice_0 furnace=b:furnace_top",
  "ghast_spawn_egg=i:spawn_eggs/spawn_egg_ghast glass_bottle=i:potion_bottle_empty glass_pane=b:glass",
  "glistering_melon_slice=i:melon_speckled glow_frame=b:glow_item_frame",
  "glow_ink_sac=i:dye_powder_black_new glow_squid_spawn_egg=i:spawn_eggs/spawn_egg_glow_squid",
  "goat_spawn_egg=i:spawn_eggs/spawn_egg_goat golden_apple=i:apple_golden golden_axe=i:gold_axe",
  "golden_boots=i:gold_boots golden_carrot=i:carrot_golden golden_chestplate=i:gold_chestplate",
  "golden_helmet=i:gold_helmet golden_hoe=i:gold_hoe golden_horse_armor=i:gold_horse_armor",
  "golden_leggings=i:gold_leggings golden_nautilus_armor=i:nautilus_armor/gold_nautilus_armor",
  "golden_pickaxe=i:gold_pickaxe golden_rail=b:rail_golden golden_shovel=i:gold_shovel",
  "golden_spear=i:spear/gold_spear golden_sword=i:gold_sword granite=b:stone_granite",
  "granite_slab=b:stone_granite granite_stairs=b:stone_granite granite_wall=b:stone_granite",
  "grass_block=b:grass_carried grass_path=b:grass_path_side gray_bundle=i:bundle_gray",
  "gray_candle=b:candles/gray_candle gray_carpet=b:wool_colored_gray gray_concrete=b:concrete_gray",
  "gray_concrete_powder=b:concrete_powder_gray gray_cushion=i:candles/gray_candle",
  "gray_dye=i:dye_powder_gray gray_glazed_terracotta=b:glazed_terracotta_gray",
  "gray_harness=i:harness/harness_gray gray_shulker_box=b:shulker_top_gray",
  "gray_stained_glass=b:glass_gray gray_stained_glass_pane=b:glass_gray",
  "gray_terracotta=b:hardened_clay_stained_gray gray_wool=b:wool_colored_gray",
  "gray_wool_double_slab=b:wool_colored_gray gray_wool_slab=b:wool_colored_gray",
  "gray_wool_stairs=b:wool_colored_gray green_bundle=i:bundle_green green_candle=b:candles/green_candle",
  "green_carpet=b:wool_colored_green green_concrete=b:concrete_green",
  "green_concrete_powder=b:concrete_powder_green green_cushion=i:candles/green_candle",
  "green_dye=i:dye_powder_green green_glazed_terracotta=b:glazed_terracotta_green",
  "green_harness=i:harness/harness_green green_shulker_box=b:shulker_top_green",
  "green_stained_glass=b:glass_green green_stained_glass_pane=b:glass_green",
  "green_terracotta=b:hardened_clay_stained_green green_wool=b:wool_colored_green",
  "green_wool_double_slab=b:wool_colored_green green_wool_slab=b:wool_colored_green",
  "green_wool_stairs=b:wool_colored_green grindstone=b:grindstone_round",
  "guardian_spawn_egg=i:spawn_eggs/spawn_egg_guardian",
  "happy_ghast_spawn_egg=i:spawn_eggs/spawn_egg_happy_ghast hay_block=b:hay_block_side",
  "heart_of_the_sea=i:heartofthesea_closed heavy_weighted_pressure_plate=b:iron_block",
  "hoglin_spawn_egg=i:spawn_eggs/spawn_egg_hoglin honey_block=b:honey_top honeycomb_block=b:honeycomb",
  "hopper_minecart=i:minecart_hopper horn_coral=b:coral_plant_yellow horn_coral_block=b:coral_yellow",
  "horn_coral_fan=b:coral_fan_yellow horse_spawn_egg=i:spawn_eggs/spawn_egg_horse",
  "husk_spawn_egg=i:spawn_eggs/spawn_egg_husk infested_chiseled_stone_bricks=b:stonebrick_carved",
  "infested_cobblestone=b:cobblestone infested_cracked_stone_bricks=b:stonebrick_cracked",
  "infested_deepslate=b:deepslate/deepslate infested_mossy_stone_bricks=b:stonebrick_mossy",
  "infested_stone=b:stone infested_stone_bricks=b:stonebrick ink_sac=i:dye_powder_black_new",
  "iron_door=i:door_iron iron_golem_spawn_egg=i:spawn_eggs/spawn_egg_iron_golem",
  "iron_nautilus_armor=i:nautilus_armor/iron_nautilus_armor iron_spear=i:spear/iron_spear",
  "jigsaw=b:jigsaw_lock jukebox=b:jukebox_side jungle_boat=i:boat_jungle jungle_button=b:planks_jungle",
  "jungle_door=i:door_jungle jungle_fence=b:planks_jungle jungle_fence_gate=b:planks_jungle",
  "jungle_hanging_sign=b:planks_jungle jungle_leaves=b:leaves_jungle jungle_log=b:log_jungle",
  "jungle_planks=b:planks_jungle jungle_pressure_plate=b:planks_jungle jungle_sapling=b:sapling_jungle",
  "jungle_sign=i:sign_jungle jungle_slab=b:planks_jungle jungle_stairs=b:planks_jungle",
  "jungle_wood=b:log_jungle lapis_lazuli=i:dye_powder_blue_new",
  "large_fern=b:double_plant_sunflower_front lava_bucket=i:bucket_lava lectern=b:lectern_top",
  "light_blue_bundle=i:bundle_light_blue light_blue_candle=b:candles/light_blue_candle",
  "light_blue_carpet=b:wool_colored_light_blue light_blue_concrete=b:concrete_light_blue",
  "light_blue_concrete_powder=b:concrete_powder_light_blue",
  "light_blue_cushion=i:candles/light_blue_candle light_blue_dye=i:dye_powder_light_blue",
  "light_blue_glazed_terracotta=b:glazed_terracotta_light_blue",
  "light_blue_harness=i:harness/harness_light_blue light_blue_shulker_box=b:shulker_top_light_blue",
  "light_blue_stained_glass=b:glass_light_blue light_blue_stained_glass_pane=b:glass_light_blue",
  "light_blue_terracotta=b:hardened_clay_stained_light_blue light_blue_wool=b:wool_colored_light_blue",
  "light_blue_wool_double_slab=b:wool_colored_light_blue light_blue_wool_slab=b:wool_colored_light_blue",
  "light_blue_wool_stairs=b:wool_colored_light_blue light_gray_bundle=i:bundle_light_gray",
  "light_gray_candle=b:candles/light_gray_candle light_gray_carpet=b:wool_colored_silver",
  "light_gray_concrete=b:concrete_silver light_gray_concrete_powder=b:concrete_powder_silver",
  "light_gray_cushion=i:candles/light_gray_candle light_gray_dye=i:dye_powder_silver",
  "light_gray_harness=i:harness/harness_light_gray light_gray_shulker_box=b:shulker_top_silver",
  "light_gray_stained_glass=b:glass_silver light_gray_stained_glass_pane=b:glass_silver",
  "light_gray_terracotta=b:hardened_clay_stained_silver light_gray_wool=b:wool_colored_silver",
  "light_gray_wool_double_slab=b:wool_colored_silver light_gray_wool_slab=b:wool_colored_silver",
  "light_gray_wool_stairs=b:wool_colored_silver light_weighted_pressure_plate=b:gold_block",
  "lilac=b:double_plant_sunflower_back lily_of_the_valley=b:flower_lily_of_the_valley",
  "lime_bundle=i:bundle_lime lime_candle=b:candles/lime_candle lime_carpet=b:wool_colored_lime",
  "lime_concrete=b:concrete_lime lime_concrete_powder=b:concrete_powder_lime",
  "lime_cushion=i:candles/lime_candle lime_dye=i:dye_powder_lime",
  "lime_glazed_terracotta=b:glazed_terracotta_lime lime_harness=i:harness/harness_lime",
  "lime_shulker_box=b:shulker_top_lime lime_stained_glass=b:glass_lime",
  "lime_stained_glass_pane=b:glass_lime lime_terracotta=b:hardened_clay_stained_lime",
  "lime_wool=b:wool_colored_lime lime_wool_double_slab=b:wool_colored_lime",
  "lime_wool_slab=b:wool_colored_lime lime_wool_stairs=b:wool_colored_lime",
  "lingering_potion=i:potion_bottle_lingering lit_pumpkin=b:pumpkin_top",
  "llama_spawn_egg=i:spawn_eggs/spawn_egg_llama lodestone=b:lodestone_top",
  "lodestone_compass=i:compass_item loom=b:loom_top magenta_bundle=i:bundle_magenta",
  "magenta_candle=b:candles/magenta_candle magenta_carpet=b:wool_colored_magenta",
  "magenta_concrete=b:concrete_magenta magenta_concrete_powder=b:concrete_powder_magenta",
  "magenta_cushion=i:candles/magenta_candle magenta_dye=i:dye_powder_magenta",
  "magenta_glazed_terracotta=b:glazed_terracotta_magenta magenta_harness=i:harness/harness_magenta",
  "magenta_shulker_box=b:shulker_top_magenta magenta_stained_glass=b:glass_magenta",
  "magenta_stained_glass_pane=b:glass_magenta magenta_terracotta=b:hardened_clay_stained_magenta",
  "magenta_wool=b:wool_colored_magenta magenta_wool_double_slab=b:wool_colored_magenta",
  "magenta_wool_slab=b:wool_colored_magenta magenta_wool_stairs=b:wool_colored_magenta",
  "magma_cube_spawn_egg=i:spawn_eggs/spawn_egg_magma_cube mangrove_button=b:mangrove_planks",
  "mangrove_fence=b:mangrove_planks mangrove_fence_gate=b:mangrove_planks",
  "mangrove_hanging_sign=b:mangrove_planks mangrove_log=b:mangrove_log_side",
  "mangrove_pressure_plate=b:mangrove_planks mangrove_roots=b:mangrove_roots_top",
  "mangrove_slab=b:mangrove_planks mangrove_stairs=b:mangrove_planks mangrove_wood=b:mangrove_log_side",
  "melon_block=b:melon_side melon_seeds=i:seeds_melon melon_slice=i:melon milk_bucket=i:bucket_milk",
  "minecart=i:minecart_normal mooshroom_spawn_egg=i:spawn_eggs/spawn_egg_mooshroom",
  "moss_carpet=b:moss_block mossy_cobblestone=b:cobblestone_mossy",
  "mossy_cobblestone_slab=b:cobblestone_mossy mossy_cobblestone_stairs=b:cobblestone_mossy",
  "mossy_cobblestone_wall=b:cobblestone_mossy mossy_stone_brick_slab=b:stonebrick_mossy",
  "mossy_stone_brick_stairs=b:stonebrick_mossy mossy_stone_brick_wall=b:stonebrick_mossy",
  "mossy_stone_bricks=b:stonebrick_mossy mud_brick_slab=b:mud_bricks mud_brick_stairs=b:mud_bricks",
  "mud_brick_wall=b:mud_bricks muddy_mangrove_roots=b:muddy_mangrove_roots_top",
  "mule_spawn_egg=i:spawn_eggs/spawn_egg_mule mushroom_stem=b:mushroom_block_skin_stem",
  "music_disc_11=i:record_11 music_disc_13=i:record_13 music_disc_5=i:record_5",
  "music_disc_blocks=i:record_blocks music_disc_cat=i:record_cat music_disc_chirp=i:record_chirp",
  "music_disc_far=i:record_far music_disc_mall=i:record_mall music_disc_mellohi=i:record_mellohi",
  "music_disc_otherside=i:record_otherside music_disc_pigstep=i:record_pigstep",
  "music_disc_stal=i:record_stal music_disc_strad=i:record_strad music_disc_wait=i:record_wait",
  "music_disc_ward=i:record_ward mutton=i:mutton_raw mycelium=b:mycelium_side nautilus_shell=i:nautilus",
  "nautilus_spawn_egg=i:spawn_eggs/spawn_egg_nautilus nether_brick_fence=b:nether_brick",
  "nether_brick_slab=b:nether_brick nether_brick_stairs=b:nether_brick nether_brick_wall=b:nether_brick",
  "netherite_nautilus_armor=i:nautilus_armor/netherite_nautilus_armor",
  "netherite_spear=i:spear/netherite_spear normal_stone_slab=b:stone normal_stone_stairs=b:stone",
  "oak_boat=i:boat_oak oak_fence=b:planks_oak oak_hanging_sign=b:planks_oak oak_leaves=b:leaves_oak",
  "oak_log=b:log_oak oak_planks=b:planks_oak oak_sapling=b:sapling_oak oak_sign=i:sign",
  "oak_slab=b:planks_oak oak_stairs=b:planks_oak oak_wood=b:log_oak observer=b:observer_top",
  "ocelot_spawn_egg=i:spawn_eggs/spawn_egg_ocelot ochre_froglight=b:ochre_froglight_side",
  "open_eyeblossom=b:eyeblossom_stem_blooming orange_bundle=i:bundle_orange",
  "orange_candle=b:candles/orange_candle orange_carpet=b:wool_colored_orange",
  "orange_concrete=b:concrete_orange orange_concrete_powder=b:concrete_powder_orange",
  "orange_cushion=i:candles/orange_candle orange_dye=i:dye_powder_orange",
  "orange_glazed_terracotta=b:glazed_terracotta_orange orange_harness=i:harness/harness_orange",
  "orange_shulker_box=b:shulker_top_orange orange_stained_glass=b:glass_orange",
  "orange_stained_glass_pane=b:glass_orange orange_terracotta=b:hardened_clay_stained_orange",
  "orange_tulip=b:flower_tulip_orange orange_wool=b:wool_colored_orange",
  "orange_wool_double_slab=b:wool_colored_orange orange_wool_slab=b:wool_colored_orange",
  "orange_wool_stairs=b:wool_colored_orange oxeye_daisy=b:flower_oxeye_daisy",
  "oxidized_copper_chain=b:oxidized_copper_chain2",
  "oxidized_copper_chest=b:oxidized_copper_chest_inventory_top",
  "oxidized_copper_golem_statue=b:oxidized_copper oxidized_cut_copper_slab=b:oxidized_cut_copper",
  "oxidized_cut_copper_stairs=b:oxidized_cut_copper packed_ice=b:ice_packed",
  "pale_hanging_moss=b:pale_hanging_moss_middle pale_moss_carpet=b:pale_moss_block",
  "pale_oak_button=b:pale_oak_planks pale_oak_fence=b:pale_oak_planks",
  "pale_oak_fence_gate=b:pale_oak_planks pale_oak_hanging_sign=b:pale_oak_planks",
  "pale_oak_log=b:pale_oak_log_side pale_oak_pressure_plate=b:pale_oak_planks",
  "pale_oak_slab=b:pale_oak_planks pale_oak_stairs=b:pale_oak_planks pale_oak_wood=b:pale_oak_log_side",
  "panda_spawn_egg=i:spawn_eggs/spawn_egg_panda parched_spawn_egg=i:spawn_eggs/spawn_egg_parched",
  "parrot_spawn_egg=i:spawn_eggs/spawn_egg_parrot pearlescent_froglight=b:pearlescent_froglight_side",
  "peony=b:double_plant_sunflower_front petrified_oak_slab=b:planks_oak",
  "phantom_spawn_egg=i:spawn_eggs/spawn_egg_phantom pig_spawn_egg=i:spawn_eggs/spawn_egg_pig",
  "piglin_brute_spawn_egg=i:spawn_eggs/spawn_egg_piglin_brute piglin_head=b:soul_sand",
  "piglin_spawn_egg=i:spawn_eggs/spawn_egg_piglin pillager_spawn_egg=i:spawn_eggs/spawn_egg_pillager",
  "pink_bundle=i:bundle_pink pink_candle=b:candles/pink_candle pink_carpet=b:wool_colored_pink",
  "pink_concrete=b:concrete_pink pink_concrete_powder=b:concrete_powder_pink",
  "pink_cushion=i:candles/pink_candle pink_dye=i:dye_powder_pink",
  "pink_glazed_terracotta=b:glazed_terracotta_pink pink_harness=i:harness/harness_pink",
  "pink_shulker_box=b:shulker_top_pink pink_stained_glass=b:glass_pink",
  "pink_stained_glass_pane=b:glass_pink pink_terracotta=b:hardened_clay_stained_pink",
  "pink_tulip=b:flower_tulip_pink pink_wool=b:wool_colored_pink",
  "pink_wool_double_slab=b:wool_colored_pink pink_wool_slab=b:wool_colored_pink",
  "pink_wool_stairs=b:wool_colored_pink piston=b:piston_side",
  "pitcher_plant=b:pitcher_crop_bottom_stage_4 player_head=b:soul_sand podzol=b:dirt_podzol_side",
  "pointed_dripstone=b:pointed_dripstone_down_base poisonous_potato=i:potato_poisonous",
  "polar_bear_spawn_egg=i:spawn_eggs/spawn_egg_polar_bear polished_andesite=b:stone_andesite_smooth",
  "polished_andesite_slab=b:stone_andesite_smooth polished_andesite_stairs=b:stone_andesite_smooth",
  "polished_basalt=b:polished_basalt_side polished_blackstone_brick_slab=b:polished_blackstone_bricks",
  "polished_blackstone_brick_stairs=b:polished_blackstone_bricks",
  "polished_blackstone_brick_wall=b:polished_blackstone_bricks",
  "polished_blackstone_button=b:polished_blackstone",
  "polished_blackstone_pressure_plate=b:polished_blackstone",
  "polished_blackstone_slab=b:polished_blackstone polished_blackstone_stairs=b:polished_blackstone",
  "polished_blackstone_wall=b:polished_blackstone polished_cinnabar_slab=b:polished_cinnabar",
  "polished_cinnabar_stairs=b:polished_cinnabar polished_cinnabar_wall=b:polished_cinnabar",
  "polished_deepslate=b:deepslate/polished_deepslate",
  "polished_deepslate_slab=b:deepslate/polished_deepslate",
  "polished_deepslate_stairs=b:deepslate/polished_deepslate",
  "polished_deepslate_wall=b:deepslate/polished_deepslate polished_diorite=b:stone_diorite_smooth",
  "polished_diorite_slab=b:stone_diorite_smooth polished_diorite_stairs=b:stone_diorite_smooth",
  "polished_granite=b:stone_granite_smooth polished_granite_slab=b:stone_granite_smooth",
  "polished_granite_stairs=b:stone_granite_smooth polished_sulfur_slab=b:polished_sulfur",
  "polished_sulfur_stairs=b:polished_sulfur polished_sulfur_wall=b:polished_sulfur",
  "polished_tuff_slab=b:polished_tuff polished_tuff_stairs=b:polished_tuff",
  "polished_tuff_wall=b:polished_tuff popped_chorus_fruit=i:chorus_fruit_popped poppy=b:flower_rose",
  "porkchop=i:porkchop_raw potion=i:potion_overlay powder_snow_bucket=i:bucket_powder_snow",
  "prismarine=b:prismarine_rough prismarine_brick_slab=b:prismarine_bricks",
  "prismarine_bricks_stairs=b:prismarine_bricks prismarine_slab=b:prismarine_rough",
  "prismarine_stairs=b:prismarine_rough prismarine_wall=b:prismarine_rough",
  "pufferfish=i:fish_pufferfish_raw pufferfish_bucket=i:bucket_pufferfish",
  "pufferfish_spawn_egg=i:spawn_eggs/spawn_egg_pufferfish pumpkin=b:pumpkin_top",
  "pumpkin_seeds=i:seeds_pumpkin purple_bundle=i:bundle_purple purple_candle=b:candles/purple_candle",
  "purple_carpet=b:wool_colored_purple purple_concrete=b:concrete_purple",
  "purple_concrete_powder=b:concrete_powder_purple purple_cushion=i:candles/purple_candle",
  "purple_dye=i:dye_powder_purple purple_glazed_terracotta=b:glazed_terracotta_purple",
  "purple_harness=i:harness/harness_purple purple_shulker_box=b:shulker_top_purple",
  "purple_stained_glass=b:glass_purple purple_stained_glass_pane=b:glass_purple",
  "purple_terracotta=b:hardened_clay_stained_purple purple_wool=b:wool_colored_purple",
  "purple_wool_double_slab=b:wool_colored_purple purple_wool_slab=b:wool_colored_purple",
  "purple_wool_stairs=b:wool_colored_purple purpur_slab=b:purpur_block purpur_stairs=b:purpur_block",
  "quartz_block=b:quartz_block_side quartz_pillar=b:quartz_block_lines quartz_slab=b:quartz_block_side",
  "quartz_stairs=b:quartz_block_side rabbit=i:rabbit_raw rabbit_spawn_egg=i:spawn_eggs/spawn_egg_rabbit",
  "rail=b:rail_normal ravager_spawn_egg=i:spawn_eggs/spawn_egg_ravager",
  "recovery_compass=i:recovery_compass_item red_bundle=i:bundle_red red_candle=b:candles/red_candle",
  "red_carpet=b:wool_colored_red red_concrete=b:concrete_red red_concrete_powder=b:concrete_powder_red",
  "red_cushion=i:candles/red_candle red_dye=i:dye_powder_red",
  "red_glazed_terracotta=b:glazed_terracotta_red red_harness=i:harness/harness_red",
  "red_mushroom=b:mushroom_red red_mushroom_block=b:mushroom_block_inside",
  "red_nether_brick_slab=b:red_nether_brick red_nether_brick_stairs=b:red_nether_brick",
  "red_nether_brick_wall=b:red_nether_brick red_sandstone=b:red_sandstone_normal",
  "red_sandstone_slab=b:red_sandstone_normal red_sandstone_stairs=b:red_sandstone_normal",
  "red_sandstone_wall=b:red_sandstone_normal red_shulker_box=b:shulker_top_red",
  "red_stained_glass=b:glass_red red_stained_glass_pane=b:glass_red",
  "red_terracotta=b:hardened_clay_stained_red red_tulip=b:flower_tulip_red red_wool=b:wool_colored_red",
  "red_wool_double_slab=b:wool_colored_red red_wool_slab=b:wool_colored_red",
  "red_wool_stairs=b:wool_colored_red redstone=b:redstone_block redstone_lamp=b:redstone_lamp_off",
  "redstone_torch=b:redstone_torch_on reinforced_deepslate=b:reinforced_deepslate_side",
  "repeating_command_block=b:repeating_command_block_conditional_mipmap resin_brick_slab=b:resin_bricks",
  "resin_brick_stairs=b:resin_bricks resin_brick_wall=b:resin_bricks",
  "respawn_anchor=b:respawn_anchor_top_off rose_bush=b:double_plant_sunflower_front",
  "salmon=i:fish_salmon_raw salmon_bucket=i:bucket_salmon",
  "salmon_spawn_egg=i:spawn_eggs/spawn_egg_salmon sandstone=b:sandstone_normal",
  "sandstone_slab=b:sandstone_normal sandstone_stairs=b:sandstone_normal",
  "sandstone_wall=b:sandstone_normal scaffolding=b:scaffolding_side",
  "sculk_catalyst=b:sculk_catalyst_side sculk_sensor=b:sculk_sensor_side",
  "sculk_shrieker=b:sculk_shrieker_side sheep_spawn_egg=i:spawn_eggs/spawn_egg_sheep",
  "shield=textures/entity/shield short_grass=b:tallgrass",
  "shulker_spawn_egg=i:spawn_eggs/spawn_egg_shulker silver_glazed_terracotta=b:glazed_terracotta_silver",
  "silverfish_spawn_egg=i:spawn_eggs/spawn_egg_silverfish",
  "skeleton_horse_spawn_egg=i:spawn_eggs/spawn_egg_skeleton_horse skeleton_skull=b:soul_sand",
  "skeleton_spawn_egg=i:spawn_eggs/spawn_egg_skeleton slime_ball=i:slimeball",
  "slime_spawn_egg=i:spawn_eggs/spawn_egg_slime small_dripleaf_block=b:small_dripleaf_top",
  "smithing_table=b:smithing_table_top smoker=b:smoker_top smooth_quartz=b:quartz_block_bottom",
  "smooth_quartz_slab=b:quartz_block_bottom smooth_quartz_stairs=b:quartz_block_bottom",
  "smooth_red_sandstone=b:red_sandstone_top smooth_red_sandstone_slab=b:red_sandstone_top",
  "smooth_red_sandstone_stairs=b:red_sandstone_top smooth_sandstone=b:sandstone_top",
  "smooth_sandstone_slab=b:sandstone_top smooth_sandstone_stairs=b:sandstone_top",
  "smooth_stone=b:stone_slab_top smooth_stone_slab=b:stone_slab_side",
  "sniffer_egg=b:sniffer_egg_not_cracked_top sniffer_spawn_egg=i:spawn_eggs/spawn_egg_sniffer",
  "snow_golem_spawn_egg=i:spawn_eggs/spawn_egg_snow_golem snow_layer=b:snow",
  "spider_spawn_egg=i:spawn_eggs/spawn_egg_spider splash_potion=i:potion_bottle_splash",
  "spore_blossom=b:spore_blossom_base spruce_boat=i:boat_spruce spruce_button=b:planks_spruce",
  "spruce_door=i:door_spruce spruce_fence=b:planks_spruce spruce_fence_gate=b:planks_spruce",
  "spruce_hanging_sign=b:planks_spruce spruce_leaves=b:leaves_spruce spruce_log=b:log_spruce",
  "spruce_planks=b:planks_spruce spruce_pressure_plate=b:planks_spruce spruce_sapling=b:sapling_spruce",
  "spruce_sign=i:sign_spruce spruce_slab=b:planks_spruce spruce_stairs=b:planks_spruce",
  "spruce_wood=b:log_spruce squid_spawn_egg=i:spawn_eggs/spawn_egg_squid sticky_piston=b:piston_side",
  "stone_brick_slab=b:stonebrick stone_brick_stairs=b:stonebrick stone_brick_wall=b:stonebrick",
  "stone_bricks=b:stonebrick stone_button=b:stone stone_pressure_plate=b:stone",
  "stone_spear=i:spear/stone_spear stone_stairs=b:cobblestone stonecutter_block=b:stonecutter2_top",
  "stray_spawn_egg=i:spawn_eggs/spawn_egg_stray strider_spawn_egg=i:spawn_eggs/spawn_egg_strider",
  "stripped_acacia_wood=b:stripped_acacia_log stripped_birch_wood=b:stripped_birch_log",
  "stripped_cherry_log=b:stripped_cherry_log_side stripped_cherry_wood=b:stripped_cherry_log_side",
  "stripped_crimson_hyphae=b:huge_fungus/stripped_crimson_stem_side",
  "stripped_crimson_stem=b:huge_fungus/stripped_crimson_stem_top",
  "stripped_dark_oak_wood=b:stripped_dark_oak_log stripped_jungle_wood=b:stripped_jungle_log",
  "stripped_mangrove_log=b:stripped_mangrove_log_side",
  "stripped_mangrove_wood=b:stripped_mangrove_log_side stripped_oak_wood=b:stripped_oak_log",
  "stripped_pale_oak_log=b:stripped_pale_oak_log_side",
  "stripped_pale_oak_wood=b:stripped_pale_oak_log_side stripped_spruce_wood=b:stripped_spruce_log",
  "stripped_warped_hyphae=b:huge_fungus/stripped_warped_stem_side",
  "stripped_warped_stem=b:huge_fungus/stripped_warped_stem_top sugar_cane=i:reeds",
  "sulfur_brick_slab=b:sulfur_bricks sulfur_brick_stairs=b:sulfur_bricks",
  "sulfur_brick_wall=b:sulfur_bricks sulfur_cube_bucket=i:bucket_sulfur_cube",
  "sulfur_cube_spawn_egg=i:spawn_eggs/spawn_egg_sulfur_cube sulfur_slab=b:sulfur",
  "sulfur_spike=b:sulfur_spike_down_base sulfur_stairs=b:sulfur sulfur_wall=b:sulfur",
  "sunflower=b:double_plant_sunflower_front suspicious_gravel=b:suspicious_gravel_0",
  "suspicious_sand=b:suspicious_sand_0 tadpole_bucket=i:bucket_tadpole",
  "tadpole_spawn_egg=i:spawn_eggs/spawn_egg_tadpole tall_grass=b:double_plant_sunflower_front",
  "target=b:target_side tnt=b:tnt_side tnt_minecart=i:minecart_tnt torch=b:torch_on",
  "totem_of_undying=i:totem trader_llama_spawn_egg=i:spawn_eggs/spawn_egg_trader_llama",
  "trapped_chest=i:market_sandik trial_spawner=b:trial_spawner_side_inactive",
  "tripwire_hook=b:trip_wire_source tropical_fish=i:fish_clownfish_raw",
  "tropical_fish_bucket=i:bucket_tropical tropical_fish_spawn_egg=i:spawn_eggs/spawn_egg_tropicalfish",
  "tube_coral=b:coral_plant_blue tube_coral_block=b:coral_blue tube_coral_fan=b:coral_fan_blue",
  "tuff_brick_slab=b:tuff_bricks tuff_brick_stairs=b:tuff_bricks tuff_brick_wall=b:tuff_bricks",
  "tuff_slab=b:tuff tuff_stairs=b:tuff tuff_wall=b:tuff turtle_egg=b:turtle_egg_not_cracked",
  "turtle_scute=i:turtle_shell_piece turtle_spawn_egg=i:spawn_eggs/spawn_egg_turtle",
  "twisting_vines=b:twisting_vines_base undyed_shulker_box=b:shulker_top_undyed vault=b:vault_top",
  "verdant_froglight=b:verdant_froglight_side vex_spawn_egg=i:spawn_eggs/spawn_egg_vex",
  "villager_spawn_egg=i:spawn_eggs/spawn_egg_villager",
  "vindicator_spawn_egg=i:spawn_eggs/spawn_egg_vindicator",
  "wandering_trader_spawn_egg=i:spawn_eggs/spawn_egg_wandering_trader",
  "warden_spawn_egg=i:spawn_eggs/spawn_egg_warden warped_button=b:huge_fungus/warped_planks",
  "warped_fence=b:huge_fungus/warped_planks warped_fence_gate=b:huge_fungus/warped_planks",
  "warped_hanging_sign=b:huge_fungus/warped_planks warped_hyphae=b:huge_fungus/warped_stem_side",
  "warped_nylium=b:warped_nylium_top warped_planks=b:huge_fungus/warped_planks",
  "warped_pressure_plate=b:huge_fungus/warped_planks warped_sign=i:sign_warped",
  "warped_slab=b:huge_fungus/warped_planks warped_stairs=b:huge_fungus/warped_planks",
  "warped_stem=b:huge_fungus/warped_stem_top warped_trapdoor=b:huge_fungus/warped_trapdoor",
  "water_bucket=i:bucket_water waterlily=b:carried_waterlily waxed_chiseled_copper=b:chiseled_copper",
  "waxed_copper=b:copper_block waxed_copper_bars=b:copper_bars waxed_copper_bulb=b:copper_bulb",
  "waxed_copper_chain=b:copper_chain2 waxed_copper_chest=b:copper_chest_inventory_top",
  "waxed_copper_door=b:copper_door_top waxed_copper_golem_statue=b:copper_block",
  "waxed_copper_grate=b:copper_grate waxed_copper_lantern=b:copper_lantern",
  "waxed_copper_trapdoor=b:copper_trapdoor waxed_cut_copper=b:cut_copper",
  "waxed_cut_copper_slab=b:cut_copper waxed_cut_copper_stairs=b:cut_copper",
  "waxed_exposed_chiseled_copper=b:exposed_chiseled_copper waxed_exposed_copper=b:exposed_copper",
  "waxed_exposed_copper_bars=b:exposed_copper_bars waxed_exposed_copper_bulb=b:exposed_copper_bulb",
  "waxed_exposed_copper_chain=b:exposed_copper_chain2",
  "waxed_exposed_copper_chest=b:exposed_copper_chest_inventory_top",
  "waxed_exposed_copper_door=b:exposed_copper_door_top",
  "waxed_exposed_copper_golem_statue=b:exposed_copper waxed_exposed_copper_grate=b:exposed_copper_grate",
  "waxed_exposed_copper_lantern=b:exposed_copper_lantern",
  "waxed_exposed_copper_trapdoor=b:exposed_copper_trapdoor",
  "waxed_exposed_cut_copper=b:exposed_cut_copper waxed_exposed_cut_copper_slab=b:exposed_cut_copper",
  "waxed_exposed_cut_copper_stairs=b:exposed_cut_copper",
  "waxed_exposed_lightning_rod=b:exposed_lightning_rod waxed_lightning_rod=b:lightning_rod",
  "waxed_oxidized_chiseled_copper=b:oxidized_chiseled_copper waxed_oxidized_copper=b:oxidized_copper",
  "waxed_oxidized_copper_bars=b:oxidized_copper_bars waxed_oxidized_copper_bulb=b:oxidized_copper_bulb",
  "waxed_oxidized_copper_chain=b:oxidized_copper_chain2",
  "waxed_oxidized_copper_chest=b:oxidized_copper_chest_inventory_top",
  "waxed_oxidized_copper_door=b:oxidized_copper_door_top",
  "waxed_oxidized_copper_golem_statue=b:oxidized_copper",
  "waxed_oxidized_copper_grate=b:oxidized_copper_grate",
  "waxed_oxidized_copper_lantern=b:oxidized_copper_lantern",
  "waxed_oxidized_copper_trapdoor=b:oxidized_copper_trapdoor",
  "waxed_oxidized_cut_copper=b:oxidized_cut_copper waxed_oxidized_cut_copper_slab=b:oxidized_cut_copper",
  "waxed_oxidized_cut_copper_stairs=b:oxidized_cut_copper",
  "waxed_oxidized_lightning_rod=b:oxidized_lightning_rod",
  "waxed_weathered_chiseled_copper=b:weathered_chiseled_copper",
  "waxed_weathered_copper=b:weathered_copper waxed_weathered_copper_bars=b:weathered_copper_bars",
  "waxed_weathered_copper_bulb=b:weathered_copper_bulb",
  "waxed_weathered_copper_chain=b:weathered_copper_chain2",
  "waxed_weathered_copper_chest=b:weathered_copper_chest_inventory_top",
  "waxed_weathered_copper_door=b:weathered_copper_door_top",
  "waxed_weathered_copper_golem_statue=b:weathered_copper",
  "waxed_weathered_copper_grate=b:weathered_copper_grate",
  "waxed_weathered_copper_lantern=b:weathered_copper_lantern",
  "waxed_weathered_copper_trapdoor=b:weathered_copper_trapdoor",
  "waxed_weathered_cut_copper=b:weathered_cut_copper",
  "waxed_weathered_cut_copper_slab=b:weathered_cut_copper",
  "waxed_weathered_cut_copper_stairs=b:weathered_cut_copper",
  "waxed_weathered_lightning_rod=b:weathered_lightning_rod",
  "weathered_copper_chain=b:weathered_copper_chain2",
  "weathered_copper_chest=b:weathered_copper_chest_inventory_top",
  "weathered_copper_golem_statue=b:weathered_copper weathered_cut_copper_slab=b:weathered_cut_copper",
  "weathered_cut_copper_stairs=b:weathered_cut_copper weeping_vines=b:weeping_vines_base",
  "wet_sponge=b:sponge_wet wheat_seeds=i:seeds_wheat white_bundle=i:bundle_white",
  "white_candle=b:candles/white_candle white_carpet=b:wool_colored_white",
  "white_concrete=b:concrete_white white_concrete_powder=b:concrete_powder_white",
  "white_cushion=i:candles/white_candle white_dye=i:dye_powder_white",
  "white_glazed_terracotta=b:glazed_terracotta_white white_harness=i:harness/harness_white",
  "white_shulker_box=b:shulker_top_white white_stained_glass=b:glass_white",
  "white_stained_glass_pane=b:glass_white white_terracotta=b:hardened_clay_stained_white",
  "white_tulip=b:flower_tulip_white white_wool=b:wool_colored_white",
  "white_wool_double_slab=b:wool_colored_white white_wool_slab=b:wool_colored_white",
  "white_wool_stairs=b:wool_colored_white witch_spawn_egg=i:spawn_eggs/spawn_egg_witch",
  "wither_rose=b:flower_wither_rose wither_skeleton_skull=b:soul_sand",
  "wither_skeleton_spawn_egg=i:spawn_eggs/spawn_egg_wither_skeleton",
  "wither_spawn_egg=i:spawn_eggs/spawn_egg_wither wolf_spawn_egg=i:spawn_eggs/spawn_egg_wolf",
  "wooden_axe=i:wood_axe wooden_button=b:planks_oak wooden_door=i:door_wood wooden_hoe=i:wood_hoe",
  "wooden_pickaxe=i:wood_pickaxe wooden_pressure_plate=b:planks_oak wooden_shovel=i:wood_shovel",
  "wooden_spear=i:spear/wood_spear wooden_sword=i:wood_sword writable_book=i:book_writable",
  "yellow_bundle=i:bundle_yellow yellow_candle=b:candles/yellow_candle",
  "yellow_carpet=b:wool_colored_yellow yellow_concrete=b:concrete_yellow",
  "yellow_concrete_powder=b:concrete_powder_yellow yellow_cushion=i:candles/yellow_candle",
  "yellow_dye=i:dye_powder_yellow yellow_glazed_terracotta=b:glazed_terracotta_yellow",
  "yellow_harness=i:harness/harness_yellow yellow_shulker_box=b:shulker_top_yellow",
  "yellow_stained_glass=b:glass_yellow yellow_stained_glass_pane=b:glass_yellow",
  "yellow_terracotta=b:hardened_clay_stained_yellow yellow_wool=b:wool_colored_yellow",
  "yellow_wool_double_slab=b:wool_colored_yellow yellow_wool_slab=b:wool_colored_yellow",
  "yellow_wool_stairs=b:wool_colored_yellow zoglin_spawn_egg=i:spawn_eggs/spawn_egg_zoglin",
  "zombie_head=b:soul_sand zombie_horse_spawn_egg=i:spawn_eggs/spawn_egg_zombie_horse",
  "zombie_nautilus_spawn_egg=i:spawn_eggs/spawn_egg_zombie_nautilus",
  "zombie_spawn_egg=i:spawn_eggs/spawn_egg_zombie",
  "zombie_villager_spawn_egg=i:spawn_eggs/spawn_egg_zombie_villager"
].join(" ");

const BLOK_GIBI_HAM = [
  "acacia_shelf acacia_trapdoor amethyst_block amethyst_cluster azalea_leaves bamboo_block bamboo_fence",
  "bamboo_fence_gate bamboo_mosaic bamboo_planks bamboo_shelf bamboo_trapdoor barrier bedrock",
  "birch_shelf birch_trapdoor blackstone blue_ice bookshelf budding_amethyst bush cactus_flower calcite",
  "cherry_leaves cherry_planks cherry_sapling cherry_shelf cherry_trapdoor chiseled_cinnabar",
  "chiseled_copper chiseled_nether_bricks chiseled_polished_blackstone chiseled_resin_bricks",
  "chiseled_sulfur chiseled_tuff chiseled_tuff_bricks chorus_flower chorus_plant cinnabar",
  "cinnabar_bricks clay coal_block coal_ore coarse_dirt cobblestone copper_bars copper_block",
  "copper_bulb copper_grate copper_lantern copper_ore copper_torch copper_trapdoor",
  "cracked_nether_bricks cracked_polished_blackstone_bricks crimson_fungus crimson_roots crimson_shelf",
  "crying_obsidian cut_copper dark_oak_shelf dark_oak_trapdoor deadbush diamond_block diamond_ore dirt",
  "dirt_with_roots dragon_egg dripstone_block emerald_block emerald_ore end_bricks end_rod end_stone",
  "exposed_chiseled_copper exposed_copper exposed_copper_bars exposed_copper_bulb exposed_copper_grate",
  "exposed_copper_lantern exposed_copper_trapdoor exposed_cut_copper exposed_lightning_rod fern",
  "firefly_bush gilded_blackstone glass glow_lichen glowstone gold_block gold_ore golden_dandelion",
  "gravel hardened_clay heavy_core ice iron_bars iron_block iron_ore iron_trapdoor jungle_shelf",
  "jungle_trapdoor ladder lantern lapis_block lapis_ore large_amethyst_bud leaf_litter lightning_rod",
  "magma mangrove_leaves mangrove_planks mangrove_propagule mangrove_shelf mangrove_trapdoor",
  "medium_amethyst_bud mob_spawner moss_block mud mud_bricks nether_brick nether_gold_ore",
  "nether_wart_block netherite_block netherrack noteblock oak_shelf obsidian oxidized_chiseled_copper",
  "oxidized_copper oxidized_copper_bars oxidized_copper_bulb oxidized_copper_grate",
  "oxidized_copper_lantern oxidized_copper_trapdoor oxidized_cut_copper oxidized_lightning_rod",
  "packed_mud pale_moss_block pale_oak_leaves pale_oak_planks pale_oak_sapling pale_oak_shelf",
  "pale_oak_trapdoor pink_petals polished_blackstone polished_blackstone_bricks polished_cinnabar",
  "polished_sulfur polished_tuff potent_sulfur prismarine_bricks purpur_block purpur_pillar",
  "quartz_bricks quartz_ore raw_copper_block raw_gold_block raw_iron_block red_nether_brick red_sand",
  "redstone_block redstone_ore resin_block resin_bricks resin_clump sand sculk sculk_vein sea_lantern",
  "sea_pickle seagrass short_dry_grass shroomlight slime small_amethyst_bud smooth_basalt snow",
  "soul_lantern soul_sand soul_soil soul_torch sponge spruce_shelf spruce_trapdoor stone",
  "stripped_acacia_log stripped_bamboo_block stripped_birch_log stripped_dark_oak_log",
  "stripped_jungle_log stripped_oak_log stripped_spruce_log structure_block structure_void sulfur",
  "sulfur_bricks tall_dry_grass tinted_glass torchflower trapdoor tuff tuff_bricks vine warped_fungus",
  "warped_roots warped_shelf warped_wart_block weathered_chiseled_copper weathered_copper",
  "weathered_copper_bars weathered_copper_bulb weathered_copper_grate weathered_copper_lantern",
  "weathered_copper_trapdoor weathered_cut_copper weathered_lightning_rod web wildflowers"
].join(" ");

// Yolu dogrudan textures/items/<id> olanlar
const ITEM_GIBI_HAM = [
  "acacia_chest_boat amethyst_shard angler_pottery_sherd apple archer_pottery_sherd armadillo_scute",
  "armor_stand arms_up_pottery_sherd arrow bamboo_chest_raft bamboo_door bamboo_raft bamboo_sign",
  "beetroot beetroot_soup birch_chest_boat blade_pottery_sherd blaze_powder blaze_rod blue_egg",
  "bolt_armor_trim_smithing_template bone bordure_indented_banner_pattern bowl bread breeze_rod",
  "brewer_pottery_sherd brewing_stand brick brown_egg brush bundle burn_pottery_sherd cake campfire",
  "carrot carrot_on_a_stick cauldron chain chainmail_boots chainmail_chestplate chainmail_helmet",
  "chainmail_leggings charcoal cherry_boat cherry_chest_boat cherry_door cherry_sign chorus_fruit",
  "clay_ball coal coast_armor_trim_smithing_template comparator cookie copper_axe copper_boots",
  "copper_chestplate copper_door copper_helmet copper_hoe copper_horse_armor copper_ingot",
  "copper_leggings copper_nugget copper_pickaxe copper_shovel copper_sword creeper_banner_pattern",
  "crimson_door danger_pottery_sherd dark_oak_chest_boat diamond diamond_axe diamond_boots",
  "diamond_chestplate diamond_helmet diamond_hoe diamond_horse_armor diamond_leggings diamond_pickaxe",
  "diamond_shovel diamond_sword disc_fragment_5 dried_kelp dune_armor_trim_smithing_template echo_shard",
  "egg elytra emerald end_crystal ender_eye ender_pearl experience_bottle explorer_pottery_sherd",
  "exposed_copper_door eye_armor_trim_smithing_template feather field_masoned_banner_pattern flint",
  "flint_and_steel flow_armor_trim_smithing_template flow_banner_pattern flow_pottery_sherd",
  "flower_banner_pattern flower_pot friend_pottery_sherd ghast_tear globe_banner_pattern glow_berries",
  "glowstone_dust goat_horn gold_ingot gold_nugget gunpowder guster_banner_pattern guster_pottery_sherd",
  "hanging_roots heart_pottery_sherd heartbreak_pottery_sherd honey_bottle honeycomb hopper",
  "host_armor_trim_smithing_template howl_pottery_sherd iron_axe iron_boots iron_chestplate iron_helmet",
  "iron_hoe iron_horse_armor iron_ingot iron_leggings iron_nugget iron_pickaxe iron_shovel iron_sword",
  "jungle_chest_boat kelp lead leather leather_boots leather_chestplate leather_helmet",
  "leather_horse_armor leather_leggings lever light_block_0 light_block_1 light_block_10 light_block_11",
  "light_block_12 light_block_13 light_block_14 light_block_15 light_block_2 light_block_3",
  "light_block_4 light_block_5 light_block_6 light_block_7 light_block_8 light_block_9 mace magma_cream",
  "mangrove_boat mangrove_chest_boat mangrove_door mangrove_sign miner_pottery_sherd",
  "mojang_banner_pattern mourner_pottery_sherd mushroom_stew music_disc_bounce music_disc_creator",
  "music_disc_creator_music_box music_disc_lava_chicken music_disc_precipice music_disc_relic",
  "music_disc_tears name_tag nether_sprouts nether_star nether_wart netherbrick netherite_axe",
  "netherite_boots netherite_chestplate netherite_helmet netherite_hoe netherite_horse_armor",
  "netherite_ingot netherite_leggings netherite_pickaxe netherite_scrap netherite_shovel",
  "netherite_sword netherite_upgrade_smithing_template oak_chest_boat ominous_bottle ominous_trial_key",
  "oxidized_copper_door painting pale_oak_boat pale_oak_chest_boat pale_oak_door pale_oak_sign paper",
  "phantom_membrane piglin_banner_pattern pitcher_pod plenty_pottery_sherd potato prismarine_crystals",
  "prismarine_shard prize_pottery_sherd pumpkin_pie quartz rabbit_foot rabbit_hide rabbit_stew",
  "raiser_armor_trim_smithing_template raw_copper raw_gold raw_iron repeater resin_brick",
  "rib_armor_trim_smithing_template rotten_flesh saddle scrape_pottery_sherd",
  "sentry_armor_trim_smithing_template shaper_armor_trim_smithing_template sheaf_pottery_sherd shears",
  "shelter_pottery_sherd shulker_shell silence_armor_trim_smithing_template skull_banner_pattern",
  "skull_pottery_sherd snort_pottery_sherd snout_armor_trim_smithing_template snowball soul_campfire",
  "spider_eye spire_armor_trim_smithing_template spruce_chest_boat spyglass stick stone_axe stone_hoe",
  "stone_pickaxe stone_shovel stone_sword string sugar suspicious_stew sweet_berries",
  "tide_armor_trim_smithing_template torchflower_seeds trial_key trident turtle_helmet",
  "vex_armor_trim_smithing_template ward_armor_trim_smithing_template warped_door",
  "warped_fungus_on_a_stick wayfinder_armor_trim_smithing_template weathered_copper_door wheat",
  "wild_armor_trim_smithing_template wind_charge wolf_armor"
].join(" ");

const HARITA = new Map();
for (const cift of HARITA_HAM.split(" ")) {
  if (!cift) continue;
  const i = cift.indexOf("=");
  if (i < 1) continue;
  const yol = cift.slice(i + 1)
    .replace(/^i:/, "textures/items/")
    .replace(/^b:/, "textures/blocks/");
  HARITA.set(cift.slice(0, i), yol);
}
for (const ad of BLOK_GIBI_HAM.split(" ")) if (ad) HARITA.set(ad, `textures/blocks/${ad}`);
for (const ad of ITEM_GIBI_HAM.split(" ")) if (ad) HARITA.set(ad, `textures/items/${ad}`);

// Esya id'sinin (minecraft: oneki olmadan) dogrulanmis texture yolu, yoksa undefined.
export function resmiIkon(ad) { return HARITA.get(ad); }
export const IKON_SAYISI = HARITA.size;
