// ============ URETIM TARIFLERI ============
// arac/tarif_guncelle.py tarafindan Mojang'in kendi tarif dosyalarindan
// uretilmistir. ELLE DUZENLEME: uretici yeniden calisinca ustune yazar.
//
// Kaynak: Mojang/bedrock-samples v1.21.90.3 behavior_pack/recipes
// 582 tarif (20 tanesi elle eklendi: Bedrock joker "dye" girdisi).
//
// Bicim: "<cikti>|<adet>|<girdi>:<adet>,<girdi>:<adet>"

const HAM = [
  "acacia_boat|1|acacia_planks:5", "acacia_door|3|acacia_planks:6", "acacia_fence_gate|1|stick:4,acacia_planks:2",
  "acacia_fence|3|acacia_planks:4,stick:2", "acacia_hanging_sign|6|chain:2,stripped_acacia_log:6", "acacia_planks|4|acacia_log:1",
  "acacia_stairs|4|acacia_planks:6", "acacia_wood|3|acacia_log:4", "activator_rail|6|iron_ingot:6,stick:2,redstone_torch:1",
  "amethyst_block|1|amethyst_shard:4", "andesite_stairs|4|andesite:6", "andesite_wall|6|andesite:6",
  "andesite|2|diorite:1,cobblestone:1", "anvil|1|iron_block:3,iron_ingot:4", "armor_stand|1|stick:6,smooth_stone_slab:1",
  "arrow|4|flint:1,stick:1,feather:1", "bamboo_block|1|bamboo:9", "bamboo_button|1|bamboo_planks:1",
  "bamboo_door|3|bamboo_planks:6", "bamboo_fence_gate|1|stick:4,bamboo_planks:2", "bamboo_fence|3|bamboo_planks:4,stick:2",
  "bamboo_hanging_sign|6|chain:2,stripped_bamboo_block:6", "bamboo_mosaic_slab|6|bamboo_mosaic:3", "bamboo_mosaic|1|bamboo_slab:2",
  "bamboo_planks|2|bamboo_block:1", "bamboo_pressure_plate|1|bamboo_planks:2", "bamboo_raft|1|bamboo_planks:5",
  "bamboo_sign|3|bamboo_planks:6,stick:1", "bamboo_slab|6|bamboo_planks:3", "bamboo_stairs|4|bamboo_planks:6",
  "bamboo_trapdoor|2|bamboo_planks:6", "banner|1|black_wool:6,stick:1", "banner|1|blue_wool:6,stick:1",
  "banner|1|brown_wool:6,stick:1", "banner|1|cyan_wool:6,stick:1", "banner|1|gray_wool:6,stick:1",
  "banner|1|green_wool:6,stick:1", "banner|1|light_blue_wool:6,stick:1", "banner|1|light_gray_wool:6,stick:1",
  "banner|1|lime_wool:6,stick:1", "banner|1|magenta_wool:6,stick:1", "banner|1|orange_wool:6,stick:1",
  "banner|1|pink_wool:6,stick:1", "banner|1|purple_wool:6,stick:1", "banner|1|red_wool:6,stick:1",
  "banner|1|white_wool:6,stick:1", "banner|1|yellow_wool:6,stick:1", "barrel|1|@planks:6,@wooden_slab:2",
  "beacon|1|glass:5,nether_star:1,obsidian:3", "bed|1|@wool:3,@planks:3", "bee_nest|1|@planks:6,honeycomb:3",
  "beehive|1|@planks:6,honeycomb:3", "beetroot_soup|1|bowl:1,beetroot:6", "bell|1|gold_ingot:3,@planks:3",
  "birch_boat|1|birch_planks:5", "birch_door|3|birch_planks:6", "birch_fence_gate|1|stick:4,birch_planks:2",
  "birch_fence|3|birch_planks:4,stick:2", "birch_hanging_sign|6|chain:2,stripped_birch_log:6", "birch_planks|4|birch_log:1",
  "birch_stairs|4|birch_planks:6", "birch_wood|3|birch_log:4", "black_candle|1|candle:1,black_dye:1",
  "black_carpet|3|black_wool:2", "black_concrete_powder|8|black_dye:1,sand:4,gravel:4", "black_stained_glass_pane|16|black_stained_glass:6",
  "black_stained_glass|8|glass:8,black_dye:1", "blackstone_slab|6|blackstone:3", "blackstone_stairs|4|blackstone:6",
  "blackstone_wall|6|blackstone:6", "blast_furnace|1|iron_ingot:5,furnace:1,smooth_stone:3", "blaze_powder|2|blaze_rod:1",
  "blue_candle|1|candle:1,blue_dye:1", "blue_carpet|3|blue_wool:2", "blue_concrete_powder|8|blue_dye:1,sand:4,gravel:4",
  "blue_ice|1|packed_ice:9", "blue_stained_glass_pane|16|blue_stained_glass:6", "blue_stained_glass|8|glass:8,blue_dye:1",
  "bone_block|1|bone_meal:9", "bone_meal|3|bone:1", "bookshelf_dummy|1|@planks:6,book:3",
  "bookshelf|1|@planks:6,book:3", "book|1|paper:3,leather:1", "bowl|4|@planks:3",
  "bow|1|stick:3,string:3", "bread|1|wheat:3", "brewing_stand|1|@stone:3,blaze_rod:1",
  "brick_block|1|brick:4", "brick_stairs|4|brick_block:6", "brick_wall|6|brick_block:6",
  "bricks|1|brick:4", "brown_candle|1|candle:1,brown_dye:1", "brown_carpet|3|brown_wool:2",
  "brown_concrete_powder|8|brown_dye:1,sand:4,gravel:4", "brown_stained_glass_pane|16|brown_stained_glass:6", "brown_stained_glass|8|glass:8,brown_dye:1",
  "brush|1|feather:1,copper_ingot:1,stick:1", "bucket|1|iron_ingot:3", "bundle|1|string:1,leather:1",
  "cake|1|milk_bucket:3,sugar:2,wheat:3,egg:1", "calibrated_sculk_sensor|1|amethyst_shard:3,sculk_sensor:1", "campfire|1|stick:3,@coals:1,@logs:3",
  "candle|1|string:1,honeycomb:1", "carrot_on_a_stick|1|fishing_rod:1,carrot:1", "cartography_table|1|@planks:4,paper:2",
  "cauldron|1|iron_ingot:7", "chain|1|iron_nugget:2,iron_ingot:1", "cherry_boat|1|cherry_planks:5",
  "cherry_button|1|cherry_planks:1", "cherry_chest_boat|1|chest:1,cherry_boat:1", "cherry_door|3|cherry_planks:6",
  "cherry_fence_gate|1|stick:4,cherry_planks:2", "cherry_fence|3|cherry_planks:4,stick:2", "cherry_hanging_sign|6|chain:2,stripped_cherry_log:6",
  "cherry_pressure_plate|1|cherry_planks:2", "cherry_sign|3|cherry_planks:6,stick:1", "cherry_slab|6|cherry_planks:3",
  "cherry_stairs|4|cherry_planks:6", "cherry_trapdoor|2|cherry_planks:6", "chest_boat|1|chest:1,boat:1",
  "chest_boat|1|chest:1,boat:1", "chest_boat|1|chest:1,boat:1", "chest_boat|1|chest:1,boat:1",
  "chest_boat|1|chest:1,boat:1", "chest_boat|1|chest:1,boat:1", "chest_boat|1|chest:1,boat:1",
  "chest_boat|1|chest:1,boat:1", "chest_minecart|1|chest:1,minecart:1", "chest|1|@planks:8",
  "chiseled_bookshelf|1|@planks:6,@wooden_slab:3", "chiseled_deepslate|1|cobbled_deepslate_slab:2", "chiseled_nether_bricks|1|nether_brick_slab:2",
  "chiseled_polished_blackstone|1|polished_blackstone_slab:2", "chiseled_tuff_bricks|1|tuff_brick_slab:2", "chiseled_tuff|1|tuff_slab:2",
  "clay|1|clay_ball:4", "clock|1|gold_ingot:4,redstone:1", "coal_block|1|coal:9",
  "coal|9|coal_block:1", "coarse_dirt|4|dirt:2,gravel:2", "cobbled_deepslate_slab|6|cobbled_deepslate:3",
  "cobbled_deepslate_stairs|4|cobbled_deepslate:6", "cobbled_deepslate_wall|6|cobbled_deepslate:6", "cobblestone_wall|6|cobblestone:6",
  "comparator|1|redstone_torch:3,quartz:1,stone:3", "compass|1|iron_ingot:4,redstone:1", "composter|1|@wooden_slab:7",
  "conduit|1|nautilus_shell:8,heart_of_the_sea:1", "cookie|8|wheat:2,cocoa_beans:1", "crafter|1|iron_ingot:5,crafting_table:1,redstone:2,dropper:1",
  "crafting_table|1|@planks:4", "creaking_heart|1|pale_oak_log:2,resin_block:1", "crimson_button|1|crimson_planks:1",
  "crimson_door|3|crimson_planks:6", "crimson_fence_gate|1|stick:4,crimson_planks:2", "crimson_fence|3|crimson_planks:4,stick:2",
  "crimson_hanging_sign|6|chain:2,stripped_crimson_stem:6", "crimson_hyphae|3|crimson_stem:4", "crimson_planks|4|crimson_stem:1",
  "crimson_pressure_plate|1|crimson_planks:2", "crimson_sign|3|crimson_planks:6,stick:1", "crimson_slab|6|crimson_planks:3",
  "crimson_stairs|4|crimson_planks:6", "crimson_trapdoor|2|crimson_planks:6", "crossbow|1|stick:3,iron_ingot:1,string:2,tripwire_hook:1",
  "cut_red_sandstone|4|red_sandstone:4", "cut_sandstone|4|sandstone:4", "cyan_candle|1|candle:1,cyan_dye:1",
  "cyan_carpet|3|cyan_wool:2", "cyan_concrete_powder|8|cyan_dye:1,sand:4,gravel:4", "cyan_stained_glass_pane|16|cyan_stained_glass:6",
  "cyan_stained_glass|8|glass:8,cyan_dye:1", "dark_oak_boat|1|dark_oak_planks:5", "dark_oak_door|3|dark_oak_planks:6",
  "dark_oak_fence_gate|1|stick:4,dark_oak_planks:2", "dark_oak_fence|3|dark_oak_planks:4,stick:2", "dark_oak_hanging_sign|6|chain:2,stripped_dark_oak_log:6",
  "dark_oak_planks|4|dark_oak_log:1", "dark_oak_stairs|4|dark_oak_planks:6", "dark_oak_wood|3|dark_oak_log:4",
  "dark_prismarine|1|prismarine_shard:8,black_dye:1", "daylight_detector|1|glass:3,quartz:3,@wooden_slab:3", "deepslate_brick_slab|6|deepslate_bricks:3",
  "deepslate_brick_stairs|4|deepslate_bricks:6", "deepslate_brick_wall|6|deepslate_bricks:6", "deepslate_bricks|4|polished_deepslate:4",
  "deepslate_tile_slab|6|deepslate_tiles:3", "deepslate_tile_stairs|4|deepslate_tiles:6", "deepslate_tile_wall|6|deepslate_tiles:6",
  "deepslate_tiles|4|deepslate_bricks:4", "detector_rail|6|iron_ingot:6,stone_pressure_plate:1,redstone:1", "diamond_axe|1|diamond:3,stick:2",
  "diamond_block|1|diamond:9", "diamond_boots|1|diamond:4", "diamond_chestplate|1|diamond:8",
  "diamond_helmet|1|diamond:5", "diamond_hoe|1|diamond:2,stick:2", "diamond_horse_armor|1|diamond:7",
  "diamond_leggings|1|diamond:7", "diamond_pickaxe|1|diamond:3,stick:2", "diamond_shovel|1|diamond:1,stick:2",
  "diamond_sword|1|diamond:2,stick:1", "diamond|9|diamond_block:1", "diorite_stairs|4|diorite:6",
  "diorite_wall|6|diorite:6", "diorite|2|cobblestone:2,quartz:2", "dispenser|1|cobblestone:7,bow:1,redstone:1",
  "dried_ghast|1|ghast_tear:8,soul_sand:1", "dried_kelp_block|1|dried_kelp:9", "dried_kelp|9|dried_kelp_block:1",
  "dripstone_block|1|pointed_dripstone:4", "dropper|1|cobblestone:7,redstone:1", "emerald_block|1|emerald:9",
  "emerald|9|emerald_block:1", "empty_map|1|paper:9", "enchanted_golden_apple|1|gold_block:8,apple:1",
  "enchanting_table|1|book:1,diamond:2,obsidian:4", "end_brick_stairs|4|end_bricks:6", "end_bricks|4|end_stone:4",
  "end_crystal|1|glass:7,ender_eye:1,ghast_tear:1", "end_rod|4|blaze_rod:1,popped_chorus_fruit:1", "ender_chest|1|obsidian:8,ender_eye:1",
  "ender_eye|1|ender_pearl:1,blaze_powder:1", "fence_gate|1|stick:4,oak_planks:2", "fermented_spider_eye|1|spider_eye:1,brown_mushroom:1,sugar:1",
  "fire_charge|3|gunpowder:1,blaze_powder:1,@coals:1", "firework_rocket|3|paper:1,gunpowder:1", "firework_star|1|gunpowder:1,red_dye:1",
  "fishing_rod|1|stick:3,string:2", "fletching_table|1|@planks:4,flint:2", "flint_and_steel|1|iron_ingot:1,flint:1",
  "flower_pot|1|brick:3", "furnace_minecart|1|minecart:1,furnace:1", "furnace|1|@stone:8",
  "glass_bottle|3|glass:3", "glass_pane|16|glass:6", "glistering_melon_slice|1|gold_nugget:8,melon_slice:1",
  "glow_item_frame|1|item_frame:1,glow_ink_sac:1", "glowstone|1|glowstone_dust:4", "gold_block|1|gold_ingot:9",
  "gold_nugget|9|gold_ingot:1", "golden_apple|1|gold_ingot:8,apple:1", "golden_axe|1|gold_ingot:3,stick:2",
  "golden_boots|1|gold_ingot:4", "golden_carrot|1|gold_nugget:8,carrot:1", "golden_chestplate|1|gold_ingot:8",
  "golden_helmet|1|gold_ingot:5", "golden_hoe|1|gold_ingot:2,stick:2", "golden_horse_armor|1|gold_ingot:7",
  "golden_leggings|1|gold_ingot:7", "golden_pickaxe|1|gold_ingot:3,stick:2", "golden_rail|6|gold_ingot:6,stick:1,redstone:1",
  "golden_shovel|1|gold_ingot:1,stick:2", "golden_sword|1|gold_ingot:2,stick:1", "granite_stairs|4|granite:6",
  "granite_wall|6|granite:6", "granite|1|diorite:1,quartz:1", "gray_candle|1|candle:1,gray_dye:1",
  "gray_carpet|3|gray_wool:2", "gray_concrete_powder|8|gray_dye:1,sand:4,gravel:4", "gray_stained_glass_pane|16|gray_stained_glass:6",
  "gray_stained_glass|8|glass:8,gray_dye:1", "green_candle|1|candle:1,green_dye:1", "green_carpet|3|green_wool:2",
  "green_concrete_powder|8|green_dye:1,sand:4,gravel:4", "green_stained_glass_pane|16|green_stained_glass:6", "green_stained_glass|8|glass:8,green_dye:1",
  "grindstone|1|stick:2,@planks:2,stone_slab:1", "hay_block|1|wheat:9", "heavy_weighted_pressure_plate|1|iron_ingot:2",
  "honey_block|1|honey_bottle:4", "honey_bottle|4|honey_block:1,glass_bottle:4", "honeycomb_block|1|honeycomb:4",
  "hopper_minecart|1|hopper:1,minecart:1", "hopper|1|iron_ingot:5,chest:1", "iron_axe|1|iron_ingot:3,stick:2",
  "iron_bars|16|iron_ingot:6", "iron_block|1|iron_ingot:9", "iron_boots|1|iron_ingot:4",
  "iron_chestplate|1|iron_ingot:8", "iron_door|3|iron_ingot:6", "iron_helmet|1|iron_ingot:5",
  "iron_hoe|1|iron_ingot:2,stick:2", "iron_horse_armor|1|iron_ingot:7", "iron_leggings|1|iron_ingot:7",
  "iron_nugget|9|iron_ingot:1", "iron_pickaxe|1|iron_ingot:3,stick:2", "iron_shovel|1|iron_ingot:1,stick:2",
  "iron_sword|1|iron_ingot:2,stick:1", "iron_trapdoor|1|iron_ingot:4", "item_frame|1|stick:8,leather:1",
  "jack_o_lantern|1|carved_pumpkin:1,torch:1", "jukebox|1|@planks:8,diamond:1", "jungle_boat|1|jungle_planks:5",
  "jungle_door|3|jungle_planks:6", "jungle_fence_gate|1|stick:4,jungle_planks:2", "jungle_fence|3|jungle_planks:4,stick:2",
  "jungle_hanging_sign|6|chain:2,stripped_jungle_log:6", "jungle_planks|4|jungle_log:1", "jungle_stairs|4|jungle_planks:6",
  "jungle_wood|3|jungle_log:4", "ladder|3|stick:7", "lantern|1|iron_nugget:8,torch:1",
  "lapis_block|1|lapis_lazuli:9", "lead|2|string:5", "leather_boots|1|leather:4",
  "leather_chestplate|1|leather:8", "leather_helmet|1|leather:5", "leather_horse_armor|1|leather:7",
  "leather_leggings|1|leather:7", "leather|1|rabbit_hide:4", "lectern|1|@wooden_slab:4,bookshelf:1",
  "lever|1|stick:1,cobblestone:1", "light_blue_candle|1|candle:1,light_blue_dye:1", "light_blue_carpet|3|light_blue_wool:2",
  "light_blue_concrete_powder|8|light_blue_dye:1,sand:4,gravel:4", "light_blue_stained_glass_pane|16|light_blue_stained_glass:6", "light_blue_stained_glass|8|glass:8,light_blue_dye:1",
  "light_gray_candle|1|candle:1,light_gray_dye:1", "light_gray_carpet|3|light_gray_wool:2", "light_gray_concrete_powder|8|light_gray_dye:1,sand:4,gravel:4",
  "light_gray_stained_glass_pane|16|light_gray_stained_glass:6", "light_gray_stained_glass|8|glass:8,light_gray_dye:1", "light_weighted_pressure_plate|1|gold_ingot:2",
  "lightning_rod|1|copper_ingot:3", "lime_candle|1|candle:1,lime_dye:1", "lime_carpet|3|lime_wool:2",
  "lime_concrete_powder|8|lime_dye:1,sand:4,gravel:4", "lime_stained_glass_pane|16|lime_stained_glass:6", "lime_stained_glass|8|glass:8,lime_dye:1",
  "lit_pumpkin|1|carved_pumpkin:1,torch:1", "lodestone|1|chiseled_stone_bricks:8,iron_ingot:1", "loom|1|@planks:2,string:2",
  "mace|1|heavy_core:1,breeze_rod:1", "magenta_candle|1|candle:1,magenta_dye:1", "magenta_carpet|3|magenta_wool:2",
  "magenta_concrete_powder|8|magenta_dye:1,sand:4,gravel:4", "magenta_stained_glass_pane|16|magenta_stained_glass:6", "magenta_stained_glass|8|glass:8,magenta_dye:1",
  "magma_cream|1|blaze_powder:1,slime_ball:1", "magma|1|magma_cream:4", "mangrove_boat|1|mangrove_planks:5",
  "mangrove_button|1|mangrove_planks:1", "mangrove_door|3|mangrove_planks:6", "mangrove_fence_gate|1|stick:4,mangrove_planks:2",
  "mangrove_fence|3|mangrove_planks:4,stick:2", "mangrove_hanging_sign|6|chain:2,stripped_mangrove_log:6", "mangrove_planks|4|mangrove_log:1",
  "mangrove_pressure_plate|1|mangrove_planks:2", "mangrove_sign|3|mangrove_planks:6,stick:1", "mangrove_slab|6|mangrove_planks:3",
  "mangrove_stairs|4|mangrove_planks:6", "mangrove_trapdoor|2|mangrove_planks:6", "mangrove_wood|3|mangrove_log:4",
  "map|1|paper:9", "melon_block|1|melon_block:9", "melon_seeds|1|melon_block:1",
  "minecart|1|iron_ingot:5", "mk:ametis_balta|1|amethyst_block:3,netherite_ingot:2", "mk:ametis_kilic|1|amethyst_block:2,netherite_ingot:2",
  "moss_carpet|3|moss_block:2", "mossy_cobblestone_stairs|4|mossy_cobblestone:6", "mossy_cobblestone_wall|6|mossy_cobblestone:6",
  "mossy_cobblestone|1|cobblestone:1,vine:1", "mossy_stone_brick_stairs|4|mossy_stone_bricks:6", "mossy_stone_brick_wall|6|mossy_stone_bricks:6",
  "mud_brick_slab|6|mud_bricks:3", "mud_brick_stairs|4|mud_bricks:6", "mud_brick_wall|6|mud_bricks:6",
  "mud_bricks|4|packed_mud:4", "muddy_mangrove_roots|1|mangrove_roots:1,mud:1", "mushroom_stew|1|brown_mushroom:1,red_mushroom:1,bowl:1",
  "name_tag|1|paper:1,iron_ingot:1", "nether_brick_fence|6|nether_brick:4,netherbrick:2", "nether_brick_stairs|4|nether_brick:6",
  "nether_brick_wall|6|nether_brick:6", "nether_bricks|1|netherbrick:4", "nether_brick|1|netherbrick:4",
  "nether_wart_block|1|nether_wart:9", "netherite_block|1|netherite_ingot:9", "netherite_ingot|1|netherite_scrap:4,gold_ingot:4",
  "normal_stone_stairs|4|stone:6", "note_block|1|@planks:8,redstone:1", "oak_boat|1|oak_planks:5",
  "oak_fence|3|oak_planks:4,stick:2", "oak_hanging_sign|6|chain:2,stripped_oak_log:6", "oak_planks|4|oak_log:1",
  "oak_stairs|4|oak_planks:6", "oak_wood|3|oak_log:4", "observer|1|cobblestone:6,redstone:2,quartz:1",
  "orange_candle|1|candle:1,orange_dye:1", "orange_carpet|3|orange_wool:2", "orange_concrete_powder|8|orange_dye:1,sand:4,gravel:4",
  "orange_stained_glass_pane|16|orange_stained_glass:6", "orange_stained_glass|8|glass:8,orange_dye:1", "packed_ice|1|ice:9",
  "packed_mud|1|mud:1,wheat:1", "painting|1|stick:8,@wool:1", "pale_moss_carpet|3|pale_moss_block:2",
  "pale_oak_boat|1|pale_oak_planks:5", "pale_oak_button|1|pale_oak_planks:1", "pale_oak_chest_boat|1|chest:1,pale_oak_boat:1",
  "pale_oak_door|3|pale_oak_planks:6", "pale_oak_fence_gate|1|stick:4,pale_oak_planks:2", "pale_oak_fence|3|pale_oak_planks:4,stick:2",
  "pale_oak_hanging_sign|6|chain:2,stripped_pale_oak_log:6", "pale_oak_pressure_plate|1|pale_oak_planks:2", "pale_oak_sign|3|pale_oak_planks:6,stick:1",
  "pale_oak_slab|6|pale_oak_planks:3", "pale_oak_stairs|4|pale_oak_planks:6", "pale_oak_trapdoor|2|pale_oak_planks:6",
  "paper|3|sugar_cane:3", "pink_candle|1|candle:1,pink_dye:1", "pink_carpet|3|pink_wool:2",
  "pink_concrete_powder|8|pink_dye:1,sand:4,gravel:4", "pink_stained_glass_pane|16|pink_stained_glass:6", "pink_stained_glass|8|glass:8,pink_dye:1",
  "piston|1|@planks:3,@stone:4,iron_ingot:1,redstone:1", "polished_andesite_stairs|4|polished_andesite:6", "polished_andesite|4|andesite:4",
  "polished_basalt|4|basalt:4", "polished_blackstone_brick_slab|6|polished_blackstone_bricks:3", "polished_blackstone_brick_stairs|4|polished_blackstone_bricks:6",
  "polished_blackstone_brick_wall|6|polished_blackstone_bricks:6", "polished_blackstone_bricks|4|polished_blackstone:4", "polished_blackstone_button|1|polished_blackstone:1",
  "polished_blackstone_pressure_plate|1|polished_blackstone:2", "polished_blackstone_slab|6|polished_blackstone:3", "polished_blackstone_stairs|4|polished_blackstone:6",
  "polished_blackstone_wall|6|polished_blackstone:6", "polished_blackstone|4|blackstone:4", "polished_deepslate_slab|6|polished_deepslate:3",
  "polished_deepslate_stairs|4|polished_deepslate:6", "polished_deepslate_wall|6|polished_deepslate:6", "polished_deepslate|4|cobbled_deepslate:4",
  "polished_diorite_stairs|4|polished_diorite:6", "polished_diorite|4|diorite:4", "polished_granite_stairs|4|polished_granite:6",
  "polished_granite|4|granite:4", "polished_tuff_slab|6|polished_tuff:3", "polished_tuff_stairs|4|polished_tuff:6",
  "polished_tuff_wall|6|polished_tuff:6", "polished_tuff|4|tuff:4", "powered_rail|6|gold_ingot:6,stick:1,redstone:1",
  "prismarine_bricks|1|prismarine_shard:9", "prismarine_stairs|4|prismarine:6", "prismarine_wall|6|prismarine:6",
  "prismarine|1|prismarine_shard:4", "pumpkin_pie|1|pumpkin:1,sugar:1,egg:1", "pumpkin_seeds|4|pumpkin:1",
  "purple_candle|1|candle:1,purple_dye:1", "purple_carpet|3|purple_wool:2", "purple_concrete_powder|8|purple_dye:1,sand:4,gravel:4",
  "purple_stained_glass_pane|16|purple_stained_glass:6", "purple_stained_glass|8|glass:8,purple_dye:1", "purpur_block|4|popped_chorus_fruit:4",
  "purpur_slab|6|purpur_pillar:3", "purpur_stairs|4|purpur_block:6", "quartz_block|1|quartz:4",
  "quartz_bricks|4|quartz_block:4", "quartz_pillar|2|quartz_block:2", "quartz_stairs|4|quartz_block:6",
  "rabbit_stew|1|cooked_rabbit:1,carrot:1,baked_potato:1,brown_mushroom:1,bowl:1", "rail|16|iron_ingot:6,stick:1", "raw_copper_block|1|raw_copper:9",
  "raw_copper|9|raw_copper_block:1", "raw_gold_block|1|raw_gold:9", "raw_gold|9|raw_gold_block:1",
  "raw_iron_block|1|raw_iron:9", "raw_iron|9|raw_iron_block:1", "recovery_compass|1|echo_shard:8,compass:1",
  "red_candle|1|candle:1,red_dye:1", "red_carpet|3|red_wool:2", "red_concrete_powder|8|red_dye:1,sand:4,gravel:4",
  "red_nether_brick_stairs|4|red_nether_brick:6", "red_nether_brick_wall|6|red_nether_brick:6", "red_nether_brick|1|netherbrick:2,nether_wart:2",
  "red_sandstone_stairs|4|red_sandstone:6", "red_sandstone_wall|6|red_sandstone:6", "red_sandstone|1|red_sand:4",
  "red_stained_glass_pane|16|red_stained_glass:6", "red_stained_glass|8|glass:8,red_dye:1", "redstone_block|1|redstone:9",
  "redstone_lamp|1|redstone:4,glowstone:1", "redstone_torch|1|redstone:1,stick:1", "redstone|9|redstone_block:1",
  "repeater|1|redstone_torch:2,redstone:1,stone:3", "resin_block|1|resin_clump:9", "resin_brick_slab|6|resin_bricks:3",
  "resin_brick_stairs|4|resin_bricks:6", "resin_brick_wall|6|resin_bricks:6", "resin_bricks|1|resin_brick:4",
  "resin_brick|1|resin_clump:1", "respawn_anchor|1|crying_obsidian:6,glowstone:3", "saddle|1|leather:3,iron_ingot:1",
  "sandstone_stairs|4|sandstone:6", "sandstone_wall|6|sandstone:6", "sandstone|1|sand:4",
  "scaffolding|6|bamboo:6,string:1", "sea_lantern|1|prismarine_shard:4,prismarine_crystals:5", "shears|1|iron_ingot:2",
  "shield|1|@planks:6,iron_ingot:1", "slime_ball|9|slime:1", "slime_block|1|slime_ball:9",
  "slime|1|slime_ball:9", "smithing_table|1|@planks:4,iron_ingot:2", "smoker|1|furnace:1,@logs:4",
  "smooth_quartz_stairs|4|smooth_quartz:6", "smooth_red_sandstone_stairs|4|smooth_red_sandstone:6", "smooth_sandstone_stairs|4|smooth_sandstone:6",
  "snow_block|1|snowball:4", "snow_layer|6|snow:3", "snow|1|snowball:4",
  "soul_campfire|1|stick:3,soul_sand:1,@logs:3", "soul_lantern|1|iron_nugget:8,soul_torch:1", "soul_torch|4|@coals:1,stick:1,soul_sand:1",
  "spruce_boat|1|spruce_planks:5", "spruce_door|3|spruce_planks:6", "spruce_fence_gate|1|stick:4,spruce_planks:2",
  "spruce_fence|3|spruce_planks:4,stick:2", "spruce_hanging_sign|6|chain:2,stripped_spruce_log:6", "spruce_planks|4|spruce_log:1",
  "spruce_stairs|4|spruce_planks:6", "spruce_wood|3|spruce_log:4", "spyglass|1|amethyst_shard:1,copper_ingot:2",
  "sticky_piston|1|slime_ball:1,piston:1", "stick|4|@planks:2", "stone_brick_stairs|4|stone_bricks:6",
  "stone_brick_wall|6|stone_bricks:6", "stone_button|1|stone:1", "stone_pressure_plate|1|stone:2",
  "stone_stairs|4|cobblestone:6", "stonecutter_block|1|iron_ingot:1,stone:3", "stonecutter|1|stone:3,iron_ingot:1",
  "stripped_mangrove_wood|3|stripped_mangrove_log:4", "sugar|1|sugar_cane:1", "target|1|hay_block:1,redstone:4",
  "tinted_glass|2|amethyst_shard:4,glass:1", "tnt_minecart|1|tnt:1,minecart:1", "tnt|1|gunpowder:5,sand:4",
  "torch|4|@coals:1,stick:1", "trapped_chest|1|chest:1,tripwire_hook:1", "tripwire_hook|2|iron_ingot:1,stick:1,@planks:1",
  "tuff_brick_slab|6|tuff_bricks:3", "tuff_brick_stairs|4|tuff_bricks:6", "tuff_brick_wall|6|tuff_bricks:6",
  "tuff_bricks|4|polished_tuff:4", "tuff_slab|6|tuff:3", "tuff_stairs|4|tuff:6",
  "tuff_wall|6|tuff:6", "turtle_helmet|1|turtle_scute:5", "undyed_shulker_box|1|shulker_shell:2,chest:1",
  "warped_button|1|warped_planks:1", "warped_door|3|warped_planks:6", "warped_fence_gate|1|stick:4,warped_planks:2",
  "warped_fence|3|warped_planks:4,stick:2", "warped_fungus_on_a_stick|1|fishing_rod:1,warped_fungus:1", "warped_hanging_sign|6|chain:2,stripped_warped_stem:6",
  "warped_hyphae|3|warped_stem:4", "warped_planks|4|warped_stem:1", "warped_pressure_plate|1|warped_planks:2",
  "warped_sign|3|warped_planks:6,stick:1", "warped_slab|6|warped_planks:3", "warped_stairs|4|warped_planks:6",
  "warped_trapdoor|2|warped_planks:6", "wheat|9|hay_block:1", "white_bed|1|@wool:3,@planks:3",
  "white_candle|1|candle:1,white_dye:1", "white_carpet|3|white_wool:2", "white_concrete_powder|8|white_dye:1,sand:4,gravel:4",
  "white_stained_glass_pane|16|white_stained_glass:6", "white_stained_glass|8|glass:8,white_dye:1", "white_wool|1|string:4",
  "wind_charge|4|breeze_rod:1", "wolf_armor|1|armadillo_scute:6", "wooden_door|3|oak_planks:6",
  "writable_book|1|book:1,ink_sac:1,feather:1", "yellow_candle|1|candle:1,yellow_dye:1", "yellow_carpet|3|yellow_wool:2",
  "yellow_concrete_powder|8|yellow_dye:1,sand:4,gravel:4", "yellow_stained_glass_pane|16|yellow_stained_glass:6", "yellow_stained_glass|8|glass:8,yellow_dye:1",
];

// Etiketli girdiler: "@planks" = herhangi bir kalas. Bedrock'un tarif
// dosyalari etiket kullaniyor, JSON dokumu bunlari cozemiyordu; en cok
// kullanilan tarifler (cubuk, sandik, meshale, firin) boyle geri geldi.
export const ETIKETLER = {
  "@planks": ["minecraft:oak_planks", "minecraft:birch_planks", "minecraft:spruce_planks", "minecraft:jungle_planks", "minecraft:acacia_planks", "minecraft:dark_oak_planks", "minecraft:mangrove_planks", "minecraft:cherry_planks", "minecraft:pale_oak_planks", "minecraft:bamboo_planks", "minecraft:crimson_planks", "minecraft:warped_planks"],
  "@logs": ["minecraft:oak_log", "minecraft:birch_log", "minecraft:spruce_log", "minecraft:jungle_log", "minecraft:acacia_log", "minecraft:dark_oak_log", "minecraft:mangrove_log", "minecraft:cherry_log", "minecraft:pale_oak_log", "minecraft:crimson_stem", "minecraft:warped_stem", "minecraft:bamboo_block"],
  "@wooden_slab": ["minecraft:oak_slab", "minecraft:birch_slab", "minecraft:spruce_slab", "minecraft:jungle_slab", "minecraft:acacia_slab", "minecraft:dark_oak_slab", "minecraft:mangrove_slab", "minecraft:cherry_slab", "minecraft:pale_oak_slab", "minecraft:bamboo_slab", "minecraft:crimson_slab", "minecraft:warped_slab"],
  "@coals": ["minecraft:coal", "minecraft:charcoal"],
  "@wool": ["minecraft:white_wool", "minecraft:orange_wool", "minecraft:magenta_wool", "minecraft:light_blue_wool", "minecraft:yellow_wool", "minecraft:lime_wool", "minecraft:pink_wool", "minecraft:gray_wool", "minecraft:light_gray_wool", "minecraft:cyan_wool", "minecraft:purple_wool", "minecraft:blue_wool", "minecraft:brown_wool", "minecraft:green_wool", "minecraft:red_wool", "minecraft:black_wool"],
  "@stone": ["minecraft:cobblestone", "minecraft:blackstone", "minecraft:cobbled_deepslate"]
};

// cikti id -> [{ n, g: [[girdi, adet], ...] }, ...]   (bir ciktinin birden
// fazla tarifi olabilir: farkli agac turleri, farkli tas turleri...)
export const TARIFLER = new Map();
for (const satir of HAM) {
  const [cikti, adet, girdiler] = satir.split("|");
  const g = girdiler.split(",").map(x => {
    const i = x.lastIndexOf(":");
    const ad = x.slice(0, i);
    return [ad.startsWith("@") || ad.includes(":") ? ad : `minecraft:${ad}`, +x.slice(i + 1)];
  });
  const id = cikti.includes(":") ? cikti : `minecraft:${cikti}`;
  if (!TARIFLER.has(id)) TARIFLER.set(id, []);
  TARIFLER.get(id).push({ n: +adet, g });
}

export const TARIF_SAYISI = HAM.length;
